-- Production constraints and indexes snapshot (2026-10-05). Test-only.
set search_path = public;
alter table achievements_config add constraint achievements_config_pkey PRIMARY KEY (id);
alter table admin_logs add constraint admin_logs_pkey PRIMARY KEY (id);
alter table admin_messages add constraint admin_messages_pkey PRIMARY KEY (id);
alter table admin_whitelist add constraint admin_whitelist_pkey PRIMARY KEY (user_id);
alter table adventure_profiles add constraint adventure_profiles_pkey PRIMARY KEY (user_id);
alter table adventure_profiles add constraint adventure_profiles_avatar_check CHECK ((avatar = ANY (ARRAY['scout'::text, 'ranger'::text, 'keeper'::text, 'artisan'::text, 'navigator'::text, 'sentinel'::text])));
alter table adventure_progress add constraint adventure_progress_pkey PRIMARY KEY (user_id, world_id);
alter table adventure_progress add constraint adventure_progress_chapter_check CHECK (((chapter >= 1) AND (chapter <= 10)));
alter table adventure_progress add constraint adventure_progress_route_check CHECK ((route = ANY (ARRAY['rhythm'::text, 'journal'::text])));
alter table adventure_rewards add constraint adventure_rewards_pkey PRIMARY KEY (user_id, world_id, chapter);
alter table adventure_rewards add constraint adventure_rewards_chapter_check CHECK (((chapter >= 1) AND (chapter <= 9)));
alter table adventure_worlds add constraint adventure_worlds_pkey PRIMARY KEY (id);
alter table adventure_worlds add constraint adventure_worlds_chapter_count_check CHECK ((chapter_count = 9));
alter table adventure_worlds add constraint adventure_worlds_id_check CHECK ((id = ANY (ARRAY['aube'::text, 'marees'::text, 'forge'::text, 'aurores'::text])));
alter table adventure_worlds add constraint adventure_worlds_tier_check CHECK ((tier = ANY (ARRAY['free'::text, 'plus'::text])));
alter table analytics_events add constraint analytics_events_pkey PRIMARY KEY (id);
alter table announcements add constraint announcements_pkey PRIMARY KEY (id);
alter table audit_logs add constraint audit_logs_pkey PRIMARY KEY (id);
alter table bosses add constraint bosses_pkey PRIMARY KEY (id);
alter table bosses add constraint bosses_reward_mult_check CHECK (((reward_mult > (0)::numeric) AND (reward_mult <= (10)::numeric)));
alter table bug_reports add constraint bug_reports_pkey PRIMARY KEY (id);
alter table campaign_state add constraint campaign_state_pkey PRIMARY KEY (user_id);
alter table coach_assignments add constraint coach_assignments_pkey PRIMARY KEY (id);
alter table coach_assignments add constraint coach_assignments_check CHECK (((status = 'completed'::text) OR (session_id IS NULL)));
alter table coach_assignments add constraint coach_assignments_instructions_check CHECK ((length(instructions) <= 2000));
alter table coach_assignments add constraint coach_assignments_planned_date_check CHECK (((planned_date >= '2000-01-01'::date) AND (planned_date <= '2100-12-31'::date)));
alter table coach_assignments add constraint coach_assignments_sport_check CHECK (((length(sport) >= 1) AND (length(sport) <= 80)));
alter table coach_assignments add constraint coach_assignments_status_check CHECK ((status = ANY (ARRAY['proposed'::text, 'accepted'::text, 'declined'::text, 'completed'::text, 'cancelled'::text])));
alter table coach_assignments add constraint coach_assignments_title_check CHECK (((length(TRIM(BOTH FROM title)) >= 1) AND (length(TRIM(BOTH FROM title)) <= 100)));
alter table coach_links add constraint coach_links_pkey PRIMARY KEY (id);
alter table coach_links add constraint coach_links_check CHECK ((coach_id <> athlete_id));
alter table coach_links add constraint coach_links_since_date_check CHECK (((since_date >= '2000-01-01'::date) AND (since_date <= '2100-12-31'::date)));
alter table coach_links add constraint coach_links_sport_check CHECK (((sport IS NULL) OR ((length(sport) >= 1) AND (length(sport) <= 80))));
alter table combat_logs add constraint combat_logs_pkey PRIMARY KEY (id);
alter table combat_logs add constraint combat_logs_damage_check CHECK ((damage >= 0));
alter table combat_logs add constraint combat_logs_enemy_type_check CHECK ((enemy_type = ANY (ARRAY['MOB'::text, 'BOSS'::text])));
alter table combat_logs add constraint combat_logs_result_check CHECK ((result = ANY (ARRAY['victory'::text, 'defeat'::text, 'escape'::text])));
alter table combat_logs add constraint combat_logs_reward_credits_check CHECK (((reward_credits >= 0) AND (reward_credits <= 10000)));
alter table combat_logs add constraint combat_logs_reward_xp_check CHECK (((reward_xp >= 0) AND (reward_xp <= 10000)));
alter table contact_messages add constraint contact_messages_pkey PRIMARY KEY (id);
alter table content_blocks add constraint content_blocks_key_key UNIQUE (key);
alter table content_blocks add constraint content_blocks_pkey PRIMARY KEY (id);
alter table contest_draws add constraint contest_draws_contest_key_draw_number_key UNIQUE (contest_key, draw_number);
alter table contest_draws add constraint contest_draws_contest_key_winner_user_id_key UNIQUE (contest_key, winner_user_id);
alter table contest_draws add constraint contest_draws_pkey PRIMARY KEY (id);
alter table contest_entries add constraint contest_entries_user_id_contest_key_key UNIQUE (user_id, contest_key);
alter table contest_entries add constraint contest_entries_pkey PRIMARY KEY (id);
alter table coupons add constraint coupons_pkey PRIMARY KEY (code);
alter table creatures add constraint creatures_slug_key UNIQUE (slug);
alter table creatures add constraint creatures_pkey PRIMARY KEY (id);
alter table daily_quests add constraint daily_quests_pkey PRIMARY KEY (id);
alter table daily_quests add constraint daily_quests_difficulty_check CHECK (((difficulty)::text = ANY ((ARRAY['facile'::character varying, 'moyen'::character varying, 'difficile'::character varying])::text[])));
alter table dynamic_pages add constraint dynamic_pages_slug_key UNIQUE (slug);
alter table dynamic_pages add constraint dynamic_pages_pkey PRIMARY KEY (id);
alter table dynamic_quests add constraint dynamic_quests_pkey PRIMARY KEY (id);
alter table friends add constraint friends_user_id_friend_id_key UNIQUE (user_id, friend_id);
alter table friends add constraint friends_pkey PRIMARY KEY (id);
alter table friendships add constraint friendships_user_id_1_user_id_2_key UNIQUE (user_id_1, user_id_2);
alter table friendships add constraint friendships_pkey PRIMARY KEY (id);
alter table fun_stats add constraint fun_stats_pkey PRIMARY KEY (id);
alter table game_settings add constraint game_settings_pkey PRIMARY KEY (id);
alter table global_config add constraint global_config_pkey PRIMARY KEY (key);
alter table guild_members add constraint guild_members_guild_id_user_id_key UNIQUE (guild_id, user_id);
alter table guild_members add constraint guild_members_user_id_key UNIQUE (user_id);
alter table guild_members add constraint guild_members_pkey PRIMARY KEY (id);
alter table guild_members add constraint guild_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'officer'::text, 'member'::text])));
alter table guild_messages add constraint guild_messages_pkey PRIMARY KEY (id);
alter table guild_messages add constraint guild_messages_content_len_check CHECK (((char_length(content) >= 1) AND (char_length(content) <= 700)));
alter table guild_raid add constraint guild_raid_pkey PRIMARY KEY (id);
alter table guilds add constraint guilds_pkey PRIMARY KEY (id);
alter table influencers add constraint influencers_pkey PRIMARY KEY (id);
alter table inventory add constraint inventory_pkey PRIMARY KEY (id);
alter table items add constraint items_pkey PRIMARY KEY (id);
alter table lore_chapters add constraint lore_chapters_slug_key UNIQUE (slug);
alter table lore_chapters add constraint lore_chapters_pkey PRIMARY KEY (id);
alter table messages add constraint messages_pkey PRIMARY KEY (id);
alter table mobs add constraint mobs_pkey PRIMARY KEY (id);
alter table mobs add constraint mobs_hp_mult_check CHECK (((hp_mult > (0)::numeric) AND (hp_mult <= (10)::numeric)));
alter table mobs add constraint mobs_reward_mult_check CHECK (((reward_mult > (0)::numeric) AND (reward_mult <= (10)::numeric)));
alter table news_updates add constraint news_updates_pkey PRIMARY KEY (id);
alter table premium_access add constraint premium_access_pkey PRIMARY KEY (id);
alter table private.coach_invites add constraint coach_invites_token_hash_key UNIQUE (token_hash);
alter table private.coach_invites add constraint coach_invites_pkey PRIMARY KEY (id);
alter table profiles add constraint profiles_friend_code_key UNIQUE (friend_code);
alter table profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table profiles add constraint profiles_role_control_check CHECK ((role = ANY (ARRAY['user'::text, 'premium'::text, 'moderator'::text, 'admin'::text, 'super_admin'::text]))) NOT VALID;
alter table profiles add constraint profiles_status_control_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text, 'banned'::text, 'deleted'::text]))) NOT VALID;
alter table referrals add constraint referrals_pkey PRIMARY KEY (id);
alter table reports add constraint reports_pkey PRIMARY KEY (id);
alter table shop_history add constraint shop_history_pkey PRIMARY KEY (id);
alter table shop_items add constraint shop_items_pkey PRIMARY KEY (id);
alter table site_settings add constraint site_settings_key_key UNIQUE (key);
alter table site_settings add constraint site_settings_pkey PRIMARY KEY (id);
alter table social_challenges add constraint social_challenges_pkey PRIMARY KEY (id);
alter table sport_goals add constraint sport_goals_pkey PRIMARY KEY (id);
alter table sport_goals add constraint sport_goals_check CHECK (((end_date >= start_date) AND ((end_date - start_date) <= 730)));
alter table sport_goals add constraint sport_goals_check1 CHECK (((start_date >= '2000-01-01'::date) AND (end_date <= '2100-01-01'::date)));
alter table sport_goals add constraint sport_goals_check2 CHECK (((metric <> ALL (ARRAY['sessions'::text, 'days'::text])) OR (target = trunc(target))));
alter table sport_goals add constraint sport_goals_metric_check CHECK ((metric = ANY (ARRAY['sessions'::text, 'days'::text, 'minutes'::text, 'distance'::text])));
alter table sport_goals add constraint sport_goals_sport_check CHECK (((sport IS NULL) OR ((length(sport) >= 1) AND (length(sport) <= 100))));
alter table sport_goals add constraint sport_goals_target_check CHECK (((target > (0)::numeric) AND (target <= (1000000)::numeric)));
alter table sport_goals add constraint sport_goals_title_check CHECK (((length(TRIM(BOTH FROM title)) >= 1) AND (length(TRIM(BOTH FROM title)) <= 100)));
alter table sports add constraint sports_pkey PRIMARY KEY (id);
alter table sports_db add constraint sports_db_pkey PRIMARY KEY (id);
alter table system_news add constraint system_news_pkey PRIMARY KEY (id);
alter table talents add constraint talents_pkey PRIMARY KEY (id);
alter table titan_admin_audit add constraint titan_admin_audit_pkey PRIMARY KEY (id);
alter table titan_admins add constraint titan_admins_pkey PRIMARY KEY (user_id);
alter table titan_admins add constraint titan_admins_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'admin'::text, 'moderator'::text])));
alter table titan_billing_events add constraint titan_billing_events_event_id_key UNIQUE (event_id);
alter table titan_billing_events add constraint titan_billing_events_pkey PRIMARY KEY (id);
alter table titan_cache_reconciliation_reports add constraint titan_cache_reconciliation_reports_pkey PRIMARY KEY (id);
alter table titan_cache_reconciliation_reports add constraint titan_cache_reconciliation_reports_status_check CHECK ((status = ANY (ARRAY['open'::text, 'reviewing'::text, 'resolved'::text, 'dismissed'::text])));
alter table titan_moderation_reports add constraint titan_moderation_reports_pkey PRIMARY KEY (id);
alter table titan_moderation_reports add constraint titan_moderation_reports_status_check CHECK ((status = ANY (ARRAY['open'::text, 'reviewing'::text, 'resolved'::text, 'dismissed'::text])));
alter table titan_public_stats_cache add constraint titan_public_stats_cache_pkey PRIMARY KEY (key);
alter table titan_social_action_log add constraint titan_social_action_log_pkey PRIMARY KEY (id);
alter table titan_social_action_log add constraint titan_social_action_log_action_check CHECK ((action = ANY (ARRAY['friend_add'::text, 'friend_remove'::text, 'block_user'::text, 'unblock_user'::text])));
alter table titan_suspicious_actions add constraint titan_suspicious_actions_pkey PRIMARY KEY (id);
alter table titan_suspicious_actions add constraint titan_suspicious_actions_severity_check CHECK ((severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])));
alter table titan_suspicious_actions add constraint titan_suspicious_actions_status_check CHECK ((status = ANY (ARRAY['open'::text, 'reviewed'::text, 'ignored'::text, 'confirmed'::text])));
alter table titan_user_blocks add constraint titan_user_blocks_pkey PRIMARY KEY (blocker_id, blocked_id);
alter table titan_user_blocks add constraint titan_user_blocks_check CHECK ((blocker_id <> blocked_id));
alter table titan_weekly_reward_usage add constraint titan_weekly_reward_usage_pkey PRIMARY KEY (user_id, week_start);
alter table titan_weekly_reward_usage add constraint titan_weekly_reward_usage_credits_awarded_check CHECK ((credits_awarded >= 0));
alter table titan_weekly_reward_usage add constraint titan_weekly_reward_usage_xp_awarded_check CHECK ((xp_awarded >= 0));
alter table training_logs add constraint training_logs_pkey PRIMARY KEY (id);
alter table training_receipts add constraint training_receipts_pkey PRIMARY KEY (user_id, client_event_id);
alter table training_revisions add constraint training_revisions_pkey PRIMARY KEY (id);
alter table user_achievements add constraint user_achievements_pkey PRIMARY KEY (user_id, achievement_id);
alter table user_bestiary add constraint user_bestiary_pkey PRIMARY KEY (user_id, enemy_key);
alter table user_bestiary add constraint user_bestiary_defeats_check CHECK ((defeats >= 0));
alter table user_bestiary add constraint user_bestiary_enemy_type_check CHECK ((enemy_type = ANY (ARRAY['MOB'::text, 'BOSS'::text])));
alter table weekly_quests add constraint weekly_quests_pkey PRIMARY KEY (id);
alter table weekly_quests add constraint weekly_quests_reward_credits_check CHECK (((reward_credits >= 0) AND (reward_credits <= 5000)));
alter table weekly_quests add constraint weekly_quests_reward_xp_check CHECK (((reward_xp >= 0) AND (reward_xp <= 5000)));
alter table weekly_quests add constraint weekly_quests_target_check CHECK (((target > 0) AND (target <= 100000)));
alter table zones add constraint zones_pkey PRIMARY KEY (id);
alter table admin_logs add constraint admin_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table admin_messages add constraint admin_messages_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES auth.users(id);
alter table admin_whitelist add constraint admin_whitelist_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table adventure_profiles add constraint adventure_profiles_selected_world_fkey FOREIGN KEY (selected_world) REFERENCES adventure_worlds(id);
alter table adventure_profiles add constraint adventure_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table adventure_progress add constraint adventure_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table adventure_progress add constraint adventure_progress_world_id_fkey FOREIGN KEY (world_id) REFERENCES adventure_worlds(id);
alter table adventure_rewards add constraint adventure_rewards_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table adventure_rewards add constraint adventure_rewards_world_id_fkey FOREIGN KEY (world_id) REFERENCES adventure_worlds(id);
alter table analytics_events add constraint analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table announcements add constraint announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table audit_logs add constraint audit_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table bug_reports add constraint bug_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table campaign_state add constraint campaign_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table coach_assignments add constraint coach_assignments_link_id_fkey FOREIGN KEY (link_id) REFERENCES coach_links(id) ON DELETE CASCADE;
alter table coach_assignments add constraint coach_assignments_session_id_fkey FOREIGN KEY (session_id) REFERENCES training_logs(id) ON DELETE SET NULL;
alter table coach_links add constraint coach_links_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table coach_links add constraint coach_links_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table combat_logs add constraint combat_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table contact_messages add constraint contact_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table content_blocks add constraint content_blocks_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table contest_draws add constraint contest_draws_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table contest_draws add constraint contest_draws_winner_user_id_fkey FOREIGN KEY (winner_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table contest_entries add constraint contest_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table creatures add constraint creatures_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table creatures add constraint creatures_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table dynamic_pages add constraint dynamic_pages_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table dynamic_pages add constraint dynamic_pages_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table friends add constraint friends_friend_id_fkey FOREIGN KEY (friend_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table friends add constraint friends_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table friendships add constraint friendships_user_id_1_fkey FOREIGN KEY (user_id_1) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table friendships add constraint friendships_user_id_2_fkey FOREIGN KEY (user_id_2) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table guild_members add constraint guild_members_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
alter table guild_members add constraint guild_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table guild_messages add constraint guild_messages_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
alter table guild_messages add constraint guild_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table guilds add constraint guilds_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table inventory add constraint inventory_item_id_fkey FOREIGN KEY (item_id) REFERENCES items(id);
alter table inventory add constraint inventory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table lore_chapters add constraint lore_chapters_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table lore_chapters add constraint lore_chapters_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table messages add constraint messages_hidden_by_fkey FOREIGN KEY (hidden_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table premium_access add constraint premium_access_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table premium_access add constraint premium_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table private.coach_invites add constraint coach_invites_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES profiles(id) ON DELETE CASCADE;
alter table private.coach_invites add constraint coach_invites_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table profiles add constraint profiles_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES guilds(id);
alter table profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table profiles add constraint profiles_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table referrals add constraint referrals_referred_user_id_fkey FOREIGN KEY (referred_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table referrals add constraint referrals_referrer_user_id_fkey FOREIGN KEY (referrer_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table reports add constraint reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table shop_history add constraint shop_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table site_settings add constraint site_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table social_challenges add constraint social_challenges_challenger_id_fkey FOREIGN KEY (challenger_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table social_challenges add constraint social_challenges_opponent_id_fkey FOREIGN KEY (opponent_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table social_challenges add constraint social_challenges_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table sport_goals add constraint sport_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table talents add constraint talents_prerequisite_id_fkey FOREIGN KEY (prerequisite_id) REFERENCES talents(id);
alter table titan_admin_audit add constraint titan_admin_audit_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_admin_audit add constraint titan_admin_audit_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_admins add constraint titan_admins_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table titan_admins add constraint titan_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table titan_billing_events add constraint titan_billing_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_cache_reconciliation_reports add constraint titan_cache_reconciliation_reports_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_cache_reconciliation_reports add constraint titan_cache_reconciliation_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table titan_moderation_reports add constraint titan_moderation_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_moderation_reports add constraint titan_moderation_reports_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_moderation_reports add constraint titan_moderation_reports_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_social_action_log add constraint titan_social_action_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table titan_social_action_log add constraint titan_social_action_log_target_id_fkey FOREIGN KEY (target_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_suspicious_actions add constraint titan_suspicious_actions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_suspicious_actions add constraint titan_suspicious_actions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table titan_user_blocks add constraint titan_user_blocks_blocked_id_fkey FOREIGN KEY (blocked_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table titan_user_blocks add constraint titan_user_blocks_blocker_id_fkey FOREIGN KEY (blocker_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table titan_weekly_reward_usage add constraint titan_weekly_reward_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table training_logs add constraint training_logs_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table training_logs add constraint training_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table training_receipts add constraint training_receipts_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table training_revisions add constraint training_revisions_log_id_fkey FOREIGN KEY (log_id) REFERENCES training_logs(id) ON DELETE CASCADE;
alter table training_revisions add constraint training_revisions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table user_achievements add constraint user_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table user_bestiary add constraint user_bestiary_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX admin_logs_action_idx ON public.admin_logs USING btree (action, target_table, created_at DESC);
CREATE INDEX admin_logs_admin_id_fk_idx ON public.admin_logs USING btree (admin_id);
CREATE INDEX admin_logs_created_idx ON public.admin_logs USING btree (created_at DESC);
CREATE INDEX admin_messages_receiver_id_fk_idx ON public.admin_messages USING btree (receiver_id);
CREATE INDEX adventure_profiles_selected_world_idx ON public.adventure_profiles USING btree (selected_world);
CREATE INDEX adventure_progress_world_idx ON public.adventure_progress USING btree (world_id);
CREATE INDEX adventure_rewards_world_idx ON public.adventure_rewards USING btree (world_id);
CREATE INDEX analytics_events_name_idx ON public.analytics_events USING btree (event_name, created_at DESC);
CREATE INDEX analytics_events_user_id_fk_idx ON public.analytics_events USING btree (user_id);
CREATE INDEX announcements_active_idx ON public.announcements USING btree (is_active, placement, priority, starts_at, ends_at);
CREATE INDEX announcements_created_by_fk_idx ON public.announcements USING btree (created_by);
CREATE INDEX audit_logs_changed_by_fk_idx ON public.audit_logs USING btree (changed_by);
CREATE INDEX bug_reports_status_idx ON public.bug_reports USING btree (status, severity, created_at DESC);
CREATE INDEX bug_reports_user_id_fk_idx ON public.bug_reports USING btree (user_id);
CREATE INDEX coach_assignments_link_date ON public.coach_assignments USING btree (link_id, planned_date);
CREATE UNIQUE INDEX coach_assignments_session_unique ON public.coach_assignments USING btree (session_id) WHERE (session_id IS NOT NULL);
CREATE UNIQUE INDEX coach_links_active_pair ON public.coach_links USING btree (coach_id, athlete_id) WHERE (revoked_at IS NULL);
CREATE INDEX coach_links_athlete ON public.coach_links USING btree (athlete_id, accepted_at);
CREATE INDEX combat_logs_user_date_idx ON public.combat_logs USING btree (user_id, created_at DESC);
CREATE INDEX contact_messages_status_idx ON public.contact_messages USING btree (status, category, created_at DESC);
CREATE INDEX contact_messages_user_id_idx ON public.contact_messages USING btree (user_id);
CREATE INDEX content_blocks_page_idx ON public.content_blocks USING btree (page, section, is_active, sort_order);
CREATE INDEX content_blocks_updated_by_fk_idx ON public.content_blocks USING btree (updated_by);
CREATE INDEX contest_draws_created_by_fk_idx ON public.contest_draws USING btree (created_by);
CREATE INDEX contest_draws_key_idx ON public.contest_draws USING btree (contest_key, draw_number);
CREATE INDEX contest_draws_winner_user_id_fk_idx ON public.contest_draws USING btree (winner_user_id);
CREATE INDEX contest_entries_key_idx ON public.contest_entries USING btree (contest_key, is_eligible, created_at);
CREATE INDEX creatures_active_idx ON public.creatures USING btree (is_active, type, sort_order);
CREATE INDEX creatures_created_by_fk_idx ON public.creatures USING btree (created_by);
CREATE INDEX creatures_updated_by_fk_idx ON public.creatures USING btree (updated_by);
CREATE INDEX dynamic_pages_created_by_fk_idx ON public.dynamic_pages USING btree (created_by);
CREATE INDEX dynamic_pages_slug_idx ON public.dynamic_pages USING btree (slug, status);
CREATE INDEX dynamic_pages_updated_by_fk_idx ON public.dynamic_pages USING btree (updated_by);
CREATE INDEX friends_friend_id_fk_idx ON public.friends USING btree (friend_id);
CREATE UNIQUE INDEX friendships_pair_unique ON public.friendships USING btree (LEAST(user_id_1, user_id_2), GREATEST(user_id_1, user_id_2));
CREATE INDEX friendships_user_1_idx ON public.friendships USING btree (user_id_1);
CREATE INDEX friendships_user_2_idx ON public.friendships USING btree (user_id_2);
CREATE INDEX guild_members_guild_idx ON public.guild_members USING btree (guild_id);
CREATE INDEX guild_members_user_idx ON public.guild_members USING btree (user_id);
CREATE INDEX guild_messages_expires_at_idx ON public.guild_messages USING btree (expires_at);
CREATE INDEX guild_messages_guild_created_idx ON public.guild_messages USING btree (guild_id, created_at DESC);
CREATE INDEX guild_messages_sender_id_idx ON public.guild_messages USING btree (sender_id);
CREATE UNIQUE INDEX guilds_code_unique_idx ON public.guilds USING btree (code) WHERE (code IS NOT NULL);
CREATE INDEX guilds_owner_idx ON public.guilds USING btree (owner_id);
CREATE INDEX influencers_status_idx ON public.influencers USING btree (status, platform, created_at DESC);
CREATE INDEX inventory_item_id_fk_idx ON public.inventory USING btree (item_id);
CREATE INDEX inventory_user_id_fk_idx ON public.inventory USING btree (user_id);
CREATE INDEX lore_chapters_created_by_fk_idx ON public.lore_chapters USING btree (created_by);
CREATE INDEX lore_chapters_status_idx ON public.lore_chapters USING btree (status, sort_order);
CREATE INDEX lore_chapters_updated_by_fk_idx ON public.lore_chapters USING btree (updated_by);
CREATE INDEX messages_created_at_idx ON public.messages USING btree (created_at DESC);
CREATE INDEX messages_expires_at_idx ON public.messages USING btree (expires_at);
CREATE INDEX messages_hidden_by_fk_idx ON public.messages USING btree (hidden_by);
CREATE INDEX messages_sender_created_idx ON public.messages USING btree (sender_id, created_at DESC);
CREATE INDEX messages_visible_created_idx ON public.messages USING btree (hidden_at, created_at DESC);
CREATE INDEX titan_news_active_idx ON public.news_updates USING btree (active, created_at DESC);
CREATE INDEX premium_access_granted_by_fk_idx ON public.premium_access USING btree (granted_by);
CREATE INDEX premium_access_user_idx ON public.premium_access USING btree (user_id, created_at DESC);
CREATE INDEX coach_invites_accepted_by_idx ON private.coach_invites USING btree (accepted_by);
CREATE INDEX coach_invites_owner ON private.coach_invites USING btree (coach_id, created_at);
CREATE INDEX idx_profiles_xp ON public.profiles USING btree (total_xp DESC);
CREATE INDEX profiles_elite_status_idx ON public.profiles USING btree (elite_status, elite_ends_at) WHERE (elite_status IS NOT NULL);
CREATE INDEX profiles_elite_subscription_idx ON public.profiles USING btree (elite_subscription_id) WHERE (elite_subscription_id IS NOT NULL);
CREATE UNIQUE INDEX profiles_friend_code_unique ON public.profiles USING btree (friend_code) WHERE (friend_code IS NOT NULL);
CREATE INDEX profiles_guild_id_fk_idx ON public.profiles USING btree (guild_id);
CREATE INDEX profiles_moderated_by_fk_idx ON public.profiles USING btree (moderated_by);
CREATE INDEX profiles_premium_idx ON public.profiles USING btree (is_premium, premium_until);
CREATE INDEX profiles_role_status_idx ON public.profiles USING btree (role, status);
CREATE INDEX titan_profiles_moderation_idx ON public.profiles USING btree (is_suspended, updated_at DESC);
CREATE INDEX referrals_referred_user_id_fk_idx ON public.referrals USING btree (referred_user_id);
CREATE INDEX referrals_referrer_user_id_fk_idx ON public.referrals USING btree (referrer_user_id);
CREATE INDEX reports_reported_user_id_fk_idx ON public.reports USING btree (reported_user_id);
CREATE INDEX shop_history_user_item_date_idx ON public.shop_history USING btree (user_id, item_id, purchased_at DESC);
CREATE INDEX shop_history_user_type_date_idx ON public.shop_history USING btree (user_id, ((economy_meta ->> 'type'::text)), purchased_at DESC);
CREATE INDEX shop_items_availability_idx ON public.shop_items USING btree (is_active, starts_at, ends_at);
CREATE INDEX site_settings_key_idx ON public.site_settings USING btree (key);
CREATE INDEX site_settings_updated_by_fk_idx ON public.site_settings USING btree (updated_by);
CREATE INDEX social_challenges_opponent_id_fk_idx ON public.social_challenges USING btree (opponent_id);
CREATE INDEX social_challenges_users_idx ON public.social_challenges USING btree (challenger_id, opponent_id, status);
CREATE INDEX social_challenges_winner_id_fk_idx ON public.social_challenges USING btree (winner_id);
CREATE INDEX sport_goals_owner_active ON public.sport_goals USING btree (user_id, archived_at);
CREATE UNIQUE INDEX sports_slug_unique_idx ON public.sports USING btree (slug) WHERE (slug IS NOT NULL);
CREATE INDEX talents_prerequisite_id_fk_idx ON public.talents USING btree (prerequisite_id);
CREATE INDEX titan_admin_audit_admin_id_fk_idx ON public.titan_admin_audit USING btree (admin_id);
CREATE INDEX titan_admin_audit_created_idx ON public.titan_admin_audit USING btree (created_at DESC);
CREATE INDEX titan_admin_audit_target_user_id_fk_idx ON public.titan_admin_audit USING btree (target_user_id);
CREATE INDEX titan_admins_created_by_fk_idx ON public.titan_admins USING btree (created_by);
CREATE INDEX titan_billing_events_occurred_at_idx ON public.titan_billing_events USING btree (user_id, occurred_at DESC) WHERE (user_id IS NOT NULL);
CREATE INDEX titan_billing_events_status_idx ON public.titan_billing_events USING btree (status, processed_at DESC);
CREATE INDEX titan_billing_events_subscription_idx ON public.titan_billing_events USING btree (subscription_id, processed_at DESC);
CREATE INDEX titan_billing_events_user_idx ON public.titan_billing_events USING btree (user_id, processed_at DESC);
CREATE INDEX titan_cache_reconciliation_reports_resolved_by_fk_idx ON public.titan_cache_reconciliation_reports USING btree (resolved_by);
CREATE INDEX titan_cache_reconciliation_status_idx ON public.titan_cache_reconciliation_reports USING btree (status, created_at DESC);
CREATE INDEX titan_cache_reconciliation_user_created_idx ON public.titan_cache_reconciliation_reports USING btree (user_id, created_at DESC);
CREATE INDEX titan_moderation_reports_reporter_id_fk_idx ON public.titan_moderation_reports USING btree (reporter_id);
CREATE INDEX titan_moderation_reports_resolved_by_fk_idx ON public.titan_moderation_reports USING btree (resolved_by);
CREATE INDEX titan_moderation_reports_target_user_id_fk_idx ON public.titan_moderation_reports USING btree (target_user_id);
CREATE INDEX titan_reports_message_idx ON public.titan_moderation_reports USING btree (message_id, created_at DESC);
CREATE INDEX titan_reports_status_idx ON public.titan_moderation_reports USING btree (status, created_at DESC);
CREATE INDEX titan_social_action_actor_idx ON public.titan_social_action_log USING btree (actor_id, action, created_at DESC);
CREATE INDEX titan_social_action_log_target_id_fk_idx ON public.titan_social_action_log USING btree (target_id);
CREATE INDEX titan_suspicious_actions_reviewed_by_fk_idx ON public.titan_suspicious_actions USING btree (reviewed_by);
CREATE INDEX titan_suspicious_actions_status_created_idx ON public.titan_suspicious_actions USING btree (status, created_at DESC);
CREATE INDEX titan_suspicious_actions_user_created_idx ON public.titan_suspicious_actions USING btree (user_id, created_at DESC);
CREATE INDEX titan_user_blocks_blocked_idx ON public.titan_user_blocks USING btree (blocked_id, created_at DESC);
CREATE INDEX titan_user_blocks_blocker_idx ON public.titan_user_blocks USING btree (blocker_id, created_at DESC);
CREATE INDEX titan_weekly_reward_usage_user_week_idx ON public.titan_weekly_reward_usage USING btree (user_id, week_start);
CREATE UNIQUE INDEX training_event_unique ON public.training_logs USING btree (user_id, client_event_id);
CREATE INDEX training_history_page ON public.training_logs USING btree (user_id, date DESC, id DESC);
CREATE INDEX training_logs_reviewed_by_fk_idx ON public.training_logs USING btree (reviewed_by);
CREATE INDEX training_logs_user_date_idx ON public.training_logs USING btree (user_id, date DESC);
CREATE INDEX training_logs_user_sport_date_idx ON public.training_logs USING btree (user_id, sport, date DESC);
CREATE INDEX training_revisions_log_idx ON public.training_revisions USING btree (log_id);
CREATE INDEX training_revisions_user_idx ON public.training_revisions USING btree (user_id);
CREATE INDEX user_achievements_user_idx ON public.user_achievements USING btree (user_id, unlocked_at DESC);
