-- Production triggers, RLS, policies and grants snapshot (2026-10-05). Test-only.
-- triggers
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.achievements_config FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.admin_logs FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.admin_messages FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.admin_whitelist FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.bosses FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER titan_combat_logs_reject_suspended BEFORE INSERT ON public.combat_logs FOR EACH ROW EXECUTE FUNCTION titan_reject_suspended_user_action();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.coupons FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.dynamic_quests FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER titan_friendships_reject_suspended BEFORE INSERT OR UPDATE ON public.friendships FOR EACH ROW EXECUTE FUNCTION titan_reject_suspended_user_action();
CREATE TRIGGER titan_guard_friendship_delete BEFORE DELETE ON public.friendships FOR EACH ROW EXECUTE FUNCTION titan_guard_friendship_delete();
CREATE TRIGGER titan_guard_friendship_insert BEFORE INSERT ON public.friendships FOR EACH ROW EXECUTE FUNCTION titan_guard_friendship_insert();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.global_config FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.guild_raid FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.inventory FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.items FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER titan_guard_message_insert BEFORE INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION titan_guard_message_insert();
CREATE TRIGGER titan_messages_reject_suspended BEFORE INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION titan_reject_suspended_user_action();
CREATE TRIGGER titan_guard_billing_fields BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION private.titan_guard_billing_fields();
CREATE TRIGGER titan_guard_profile_privileges BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION private.titan_guard_profile_privileges();
CREATE TRIGGER titan_guard_profile_progression_trigger BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION titan_guard_profile_progression();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.reports FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER titan_shop_history_reject_suspended BEFORE INSERT ON public.shop_history FOR EACH ROW EXECUTE FUNCTION titan_reject_suspended_user_action();
CREATE TRIGGER titan_social_challenges_reject_suspended BEFORE INSERT OR UPDATE ON public.social_challenges FOR EACH ROW EXECUTE FUNCTION titan_reject_suspended_user_action();
CREATE TRIGGER sport_goal_guard BEFORE INSERT OR UPDATE ON public.sport_goals FOR EACH ROW EXECUTE FUNCTION private.titan_guard_sport_goal();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.sports_db FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.system_news FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
CREATE TRIGGER titan_guard_training_log_trigger BEFORE INSERT OR UPDATE ON public.training_logs FOR EACH ROW EXECUTE FUNCTION titan_guard_training_log();
CREATE TRIGGER titan_training_logs_reject_suspended BEFORE INSERT ON public.training_logs FOR EACH ROW EXECUTE FUNCTION titan_reject_suspended_user_action();
CREATE TRIGGER titan_user_achievements_reject_suspended BEFORE INSERT ON public.user_achievements FOR EACH ROW EXECUTE FUNCTION titan_reject_suspended_user_action();
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER audit_trigger AFTER INSERT OR DELETE OR UPDATE ON public.zones FOR EACH ROW EXECUTE FUNCTION handle_audit_log();
-- rls
alter table public.achievements_config enable row level security;
alter table public.admin_logs enable row level security;
alter table public.admin_messages enable row level security;
alter table public.admin_whitelist enable row level security;
alter table public.adventure_profiles enable row level security;
alter table public.adventure_progress enable row level security;
alter table public.adventure_rewards enable row level security;
alter table public.adventure_worlds enable row level security;
alter table public.analytics_events enable row level security;
alter table public.announcements enable row level security;
alter table public.audit_logs enable row level security;
alter table public.bosses enable row level security;
alter table public.bug_reports enable row level security;
alter table public.campaign_state enable row level security;
alter table public.coach_assignments enable row level security;
alter table private.coach_invites enable row level security;
alter table public.coach_links enable row level security;
alter table public.combat_logs enable row level security;
alter table public.contact_messages enable row level security;
alter table public.content_blocks enable row level security;
alter table public.contest_draws enable row level security;
alter table public.contest_entries enable row level security;
alter table public.coupons enable row level security;
alter table public.creatures enable row level security;
alter table public.daily_quests enable row level security;
alter table public.dynamic_pages enable row level security;
alter table public.dynamic_quests enable row level security;
alter table public.friends enable row level security;
alter table public.friendships enable row level security;
alter table public.fun_stats enable row level security;
alter table public.game_settings enable row level security;
alter table public.global_config enable row level security;
alter table public.guild_members enable row level security;
alter table public.guild_messages enable row level security;
alter table public.guild_raid enable row level security;
alter table public.guilds enable row level security;
alter table public.influencers enable row level security;
alter table public.inventory enable row level security;
alter table public.items enable row level security;
alter table public.lore_chapters enable row level security;
alter table public.messages enable row level security;
alter table public.mobs enable row level security;
alter table public.news_updates enable row level security;
alter table public.premium_access enable row level security;
alter table public.profiles enable row level security;
alter table public.referrals enable row level security;
alter table public.reports enable row level security;
alter table public.shop_history enable row level security;
alter table public.shop_items enable row level security;
alter table public.site_settings enable row level security;
alter table public.social_challenges enable row level security;
alter table public.sport_goals enable row level security;
alter table public.sports enable row level security;
alter table public.sports_db enable row level security;
alter table public.system_news enable row level security;
alter table public.talents enable row level security;
alter table public.titan_admin_audit enable row level security;
alter table public.titan_admins enable row level security;
alter table public.titan_billing_events enable row level security;
alter table public.titan_cache_reconciliation_reports enable row level security;
alter table public.titan_moderation_reports enable row level security;
alter table public.titan_public_stats_cache enable row level security;
alter table public.titan_social_action_log enable row level security;
alter table public.titan_suspicious_actions enable row level security;
alter table public.titan_user_blocks enable row level security;
alter table public.titan_weekly_reward_usage enable row level security;
alter table public.training_logs enable row level security;
alter table public.training_receipts enable row level security;
alter table public.training_revisions enable row level security;
alter table public.user_achievements enable row level security;
alter table public.user_bestiary enable row level security;
alter table public.weekly_quests enable row level security;
alter table public.zones enable row level security;
-- policies
create policy "Lecture Publique Trophees" on public.achievements_config as PERMISSIVE for SELECT to public using (true);
create policy "Public Read" on public.achievements_config as PERMISSIVE for SELECT to public using (true);
create policy "Public Read Achievements" on public.achievements_config as PERMISSIVE for SELECT to public using (true);
create policy "Read Public Achievements" on public.achievements_config as PERMISSIVE for SELECT to public using (true);
create policy achievements_config_admin_all_v79 on public.achievements_config as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy game_data_public_read_achievements on public.achievements_config as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy titan_catalog_public_read on public.achievements_config as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy admin_logs_admin_insert_v1 on public.admin_logs as PERMISSIVE for INSERT to authenticated with check ((private.titan_is_admin(( SELECT auth.uid() AS uid)) AND ((admin_id = ( SELECT auth.uid() AS uid)) OR (admin_id IS NULL))));
create policy admin_logs_admin_select_v1 on public.admin_logs as PERMISSIVE for SELECT to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy admin_messages_closed_deny_v79 on public.admin_messages as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy "Public Read Whitelist" on public.admin_whitelist as PERMISSIVE for SELECT to authenticated using (true);
create policy adventure_profiles_owner on public.adventure_profiles as PERMISSIVE for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id));
create policy adventure_progress_owner on public.adventure_progress as PERMISSIVE for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id));
create policy adventure_rewards_owner on public.adventure_rewards as PERMISSIVE for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id));
create policy adventure_worlds_read on public.adventure_worlds as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy analytics_events_admin_select_v1 on public.analytics_events as PERMISSIVE for SELECT to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy analytics_events_public_insert_v1 on public.analytics_events as PERMISSIVE for INSERT to anon, authenticated with check (((user_id IS NULL) OR (user_id = ( SELECT auth.uid() AS uid))));
create policy announcements_admin_all_v1 on public.announcements as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy announcements_public_select_v1 on public.announcements as PERMISSIVE for SELECT to anon, authenticated using ((((is_active IS TRUE) AND ((starts_at IS NULL) OR (starts_at <= now())) AND ((ends_at IS NULL) OR (ends_at >= now()))) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy audit_logs_closed_deny_v79 on public.audit_logs as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy "Public Read Bosses" on public.bosses as PERMISSIVE for SELECT to public using (true);
create policy bosses_admin_all_v1 on public.bosses as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy game_data_public_read_bosses on public.bosses as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy titan_catalog_public_read on public.bosses as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy bug_reports_admin_update_v1 on public.bug_reports as PERMISSIVE for UPDATE to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy bug_reports_public_insert_v1 on public.bug_reports as PERMISSIVE for INSERT to anon, authenticated with check (((user_id IS NULL) OR (user_id = ( SELECT auth.uid() AS uid))));
create policy bug_reports_self_or_admin_select_v1 on public.bug_reports as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy "Insérer sa propre campagne" on public.campaign_state as PERMISSIVE for INSERT to public with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Mettre à jour sa propre campagne" on public.campaign_state as PERMISSIVE for UPDATE to public using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Voir sa propre campagne" on public.campaign_state as PERMISSIVE for SELECT to public using ((( SELECT auth.uid() AS uid) = user_id));
create policy coach_assignments_participants on public.coach_assignments as PERMISSIVE for SELECT to authenticated using ((EXISTS ( SELECT 1
   FROM coach_links l
  WHERE ((l.id = coach_assignments.link_id) AND (l.revoked_at IS NULL) AND ((( SELECT auth.uid() AS uid) = l.coach_id) OR (( SELECT auth.uid() AS uid) = l.athlete_id))))));
create policy coach_links_participants on public.coach_links as PERMISSIVE for SELECT to authenticated using (((( SELECT auth.uid() AS uid) = coach_id) OR (( SELECT auth.uid() AS uid) = athlete_id)));
create policy combat_logs_select_own on public.combat_logs as PERMISSIVE for SELECT to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy contact_messages_admin_all_v1 on public.contact_messages as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy contact_messages_public_insert_v79 on public.contact_messages as PERMISSIVE for INSERT to anon, authenticated with check ((((user_id IS NULL) OR (user_id = ( SELECT auth.uid() AS uid))) AND ((char_length(btrim(message)) >= 10) AND (char_length(btrim(message)) <= 3000)) AND ((name IS NULL) OR ((char_length(btrim(name)) >= 1) AND (char_length(btrim(name)) <= 120))) AND ((subject IS NULL) OR (char_length(btrim(subject)) <= 180)) AND ((email IS NULL) OR (btrim(email) = ''::text) OR ((char_length(btrim(email)) <= 180) AND (btrim(email) ~* '^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}$'::text))) AND ((char_length(btrim(category)) >= 2) AND (char_length(btrim(category)) <= 40)) AND (status = 'new'::text) AND (priority = 'normal'::text) AND (admin_note IS NULL)));
create policy content_blocks_admin_all_v1 on public.content_blocks as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy content_blocks_public_select_v1 on public.content_blocks as PERMISSIVE for SELECT to anon, authenticated using (((is_active IS TRUE) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy contest_draws_admin_all_v1 on public.contest_draws as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy contest_draws_admin_select_v1 on public.contest_draws as PERMISSIVE for SELECT to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy contest_entries_admin_all_v1 on public.contest_entries as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy contest_entries_self_insert_v1 on public.contest_entries as PERMISSIVE for INSERT to authenticated with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy contest_entries_self_or_admin_select_v1 on public.contest_entries as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy "Super Admin Coupons" on public.coupons as PERMISSIVE for ALL to authenticated using ((( SELECT auth.uid() AS uid) = '080d9fef-bf59-4396-99e7-c048157635b7'::uuid));
create policy creatures_admin_all_v1 on public.creatures as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy creatures_public_select_v1 on public.creatures as PERMISSIVE for SELECT to anon, authenticated using (((is_active IS TRUE) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy daily_quests_closed_deny_v79 on public.daily_quests as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy dynamic_pages_admin_all_v1 on public.dynamic_pages as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy dynamic_pages_public_select_v1 on public.dynamic_pages as PERMISSIVE for SELECT to anon, authenticated using (((status = 'published'::text) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy "Public Read" on public.dynamic_quests as PERMISSIVE for SELECT to public using (true);
create policy "Super Admin Quests" on public.dynamic_quests as PERMISSIVE for ALL to authenticated using ((( SELECT auth.uid() AS uid) = '080d9fef-bf59-4396-99e7-c048157635b7'::uuid));
create policy dynamic_quests_admin_all_v79 on public.dynamic_quests as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy titan_dynamic_quests_select_all on public.dynamic_quests as PERMISSIVE for SELECT to authenticated using (true);
create policy "Users can add friends" on public.friends as PERMISSIVE for INSERT to public with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can see their own friends" on public.friends as PERMISSIVE for SELECT to public using (((( SELECT auth.uid() AS uid) = user_id) OR (( SELECT auth.uid() AS uid) = friend_id)));
create policy "Users can update friendship status" on public.friends as PERMISSIVE for UPDATE to public using (((( SELECT auth.uid() AS uid) = friend_id) OR (( SELECT auth.uid() AS uid) = user_id)));
create policy friendships_delete_involved on public.friendships as PERMISSIVE for DELETE to authenticated using (((user_id_1 = ( SELECT auth.uid() AS uid)) OR (user_id_2 = ( SELECT auth.uid() AS uid))));
create policy friendships_insert_own on public.friendships as PERMISSIVE for INSERT to authenticated with check (((user_id_1 = ( SELECT auth.uid() AS uid)) AND (user_id_2 <> ( SELECT auth.uid() AS uid))));
create policy friendships_select_involved on public.friendships as PERMISSIVE for SELECT to authenticated using (((user_id_1 = ( SELECT auth.uid() AS uid)) OR (user_id_2 = ( SELECT auth.uid() AS uid))));
create policy "Lecture publique fun_stats" on public.fun_stats as PERMISSIVE for SELECT to public using (true);
create policy "Public Read" on public.fun_stats as PERMISSIVE for SELECT to public using (true);
create policy "Read Fun Stats" on public.fun_stats as PERMISSIVE for SELECT to public using (true);
create policy fun_stats_admin_all_v79 on public.fun_stats as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy game_data_public_read_fun_stats on public.fun_stats as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy titan_catalog_public_read on public.fun_stats as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy game_settings_closed_deny_v79 on public.game_settings as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy "Public Read" on public.global_config as PERMISSIVE for SELECT to public using (true);
create policy "Public Read Config" on public.global_config as PERMISSIVE for SELECT to authenticated using (true);
create policy "Read Global Config" on public.global_config as PERMISSIVE for SELECT to public using (true);
create policy "Super Admin Config" on public.global_config as PERMISSIVE for ALL to authenticated using ((( SELECT auth.uid() AS uid) = '080d9fef-bf59-4396-99e7-c048157635b7'::uuid));
create policy game_data_public_read_global_config on public.global_config as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy global_config_admin_all_v79 on public.global_config as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy titan_catalog_public_read on public.global_config as PERMISSIVE for SELECT to anon, authenticated using ((COALESCE(is_active, true) IS TRUE));
create policy guild_members_delete_self_or_owner on public.guild_members as PERMISSIVE for DELETE to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
   FROM guilds g
  WHERE ((g.id = guild_members.guild_id) AND (g.owner_id = ( SELECT auth.uid() AS uid)))))));
create policy guild_members_insert_self on public.guild_members as PERMISSIVE for INSERT to authenticated with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy guild_members_select_same_guild on public.guild_members as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
   FROM guild_members mine
  WHERE ((mine.guild_id = guild_members.guild_id) AND (mine.user_id = ( SELECT auth.uid() AS uid)))))));
create policy guild_messages_member_select on public.guild_messages as PERMISSIVE for SELECT to authenticated using (((hidden IS FALSE) AND (EXISTS ( SELECT 1
   FROM guild_members gm
  WHERE ((gm.guild_id = guild_messages.guild_id) AND (gm.user_id = ( SELECT auth.uid() AS uid)))))));
create policy guild_raid_closed_until_schema_owner on public.guild_raid as PERMISSIVE for ALL to authenticated using (false) with check (false);
create policy guilds_member_select on public.guilds as PERMISSIVE for SELECT to authenticated using (((owner_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
   FROM guild_members gm
  WHERE ((gm.guild_id = guilds.id) AND (gm.user_id = ( SELECT auth.uid() AS uid)))))));
create policy guilds_owner_write on public.guilds as PERMISSIVE for ALL to authenticated using ((owner_id = ( SELECT auth.uid() AS uid))) with check ((owner_id = ( SELECT auth.uid() AS uid)));
create policy influencers_admin_all_v1 on public.influencers as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy inventory_own_all on public.inventory as PERMISSIVE for ALL to authenticated using ((user_id = ( SELECT auth.uid() AS uid))) with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy "Items visibles par tous" on public.items as PERMISSIVE for SELECT to public using (true);
create policy "Lecture items publique" on public.items as PERMISSIVE for SELECT to authenticated using (true);
create policy "Public Read Items" on public.items as PERMISSIVE for SELECT to public using (true);
create policy items_admin_all_v79 on public.items as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy lore_admin_all_v1 on public.lore_chapters as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy lore_public_select_v1 on public.lore_chapters as PERMISSIVE for SELECT to anon, authenticated using (((status = 'published'::text) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy messages_select_authenticated_visible on public.messages as PERMISSIVE for SELECT to authenticated using (((COALESCE(expires_at, (created_at + '48:00:00'::interval)) > now()) AND ((hidden_at IS NULL) OR (sender_id = ( SELECT auth.uid() AS uid)) OR titan_is_admin(( SELECT auth.uid() AS uid)))));
create policy "Public Read Mobs" on public.mobs as PERMISSIVE for SELECT to public using (true);
create policy game_data_public_read_mobs on public.mobs as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy mobs_admin_all_v1 on public.mobs as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy titan_catalog_public_read on public.mobs as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy news_updates_public_active on public.news_updates as PERMISSIVE for SELECT to anon, authenticated using ((active = true));
create policy premium_access_admin_all_v1 on public.premium_access as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy premium_access_self_or_admin_select_v1 on public.premium_access as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy profiles_admin_update_v78 on public.profiles as PERMISSIVE for UPDATE to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy profiles_self_or_admin_select_v1 on public.profiles as PERMISSIVE for SELECT to authenticated using (((id = ( SELECT auth.uid() AS uid)) OR private.titan_is_moderator_or_admin(( SELECT auth.uid() AS uid))));
create policy referrals_admin_all_v1 on public.referrals as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy referrals_self_or_admin_select_v1 on public.referrals as PERMISSIVE for SELECT to authenticated using (((referrer_user_id = ( SELECT auth.uid() AS uid)) OR (referred_user_id = ( SELECT auth.uid() AS uid)) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy "Users can create reports" on public.reports as PERMISSIVE for INSERT to public with check ((( SELECT auth.uid() AS uid) = reporter_id));
create policy reports_admin_update_v1 on public.reports as PERMISSIVE for UPDATE to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy reports_self_or_admin_select_v1 on public.reports as PERMISSIVE for SELECT to authenticated using (((reporter_id = ( SELECT auth.uid() AS uid)) OR (reported_id = ( SELECT auth.uid() AS uid)) OR (reported_user_id = ( SELECT auth.uid() AS uid)) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy shop_history_insert_own_v89 on public.shop_history as PERMISSIVE for INSERT to authenticated with check ((( SELECT auth.uid() AS uid) = user_id));
create policy shop_history_select_own_v89 on public.shop_history as PERMISSIVE for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id));
create policy shop_items_admin_delete_v89 on public.shop_items as PERMISSIVE for DELETE to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy shop_items_admin_insert_v89 on public.shop_items as PERMISSIVE for INSERT to authenticated with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy shop_items_admin_update_v89 on public.shop_items as PERMISSIVE for UPDATE to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy shop_items_visible_catalog_v89 on public.shop_items as PERMISSIVE for SELECT to anon, authenticated using ((((COALESCE(is_active, true) IS TRUE) AND ((starts_at IS NULL) OR (starts_at <= now())) AND ((ends_at IS NULL) OR (ends_at >= now()))) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy site_settings_admin_all_v1 on public.site_settings as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy site_settings_public_select_v1 on public.site_settings as PERMISSIVE for SELECT to anon, authenticated using (((is_public IS TRUE) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy social_challenges_insert_own on public.social_challenges as PERMISSIVE for INSERT to authenticated with check ((challenger_id = ( SELECT auth.uid() AS uid)));
create policy social_challenges_involved_all on public.social_challenges as PERMISSIVE for ALL to authenticated using (((challenger_id = ( SELECT auth.uid() AS uid)) OR (opponent_id = ( SELECT auth.uid() AS uid)))) with check (((challenger_id = ( SELECT auth.uid() AS uid)) OR (opponent_id = ( SELECT auth.uid() AS uid))));
create policy social_challenges_select_involved on public.social_challenges as PERMISSIVE for SELECT to authenticated using (((challenger_id = ( SELECT auth.uid() AS uid)) OR (opponent_id = ( SELECT auth.uid() AS uid))));
create policy social_challenges_update_involved on public.social_challenges as PERMISSIVE for UPDATE to authenticated using (((challenger_id = ( SELECT auth.uid() AS uid)) OR (opponent_id = ( SELECT auth.uid() AS uid)))) with check (((challenger_id = ( SELECT auth.uid() AS uid)) OR (opponent_id = ( SELECT auth.uid() AS uid))));
create policy sport_goals_insert on public.sport_goals as PERMISSIVE for INSERT to authenticated with check ((( SELECT auth.uid() AS uid) = user_id));
create policy sport_goals_read on public.sport_goals as PERMISSIVE for SELECT to authenticated using ((( SELECT auth.uid() AS uid) = user_id));
create policy sport_goals_update on public.sport_goals as PERMISSIVE for UPDATE to authenticated using ((( SELECT auth.uid() AS uid) = user_id)) with check ((( SELECT auth.uid() AS uid) = user_id));
create policy sports_admin_all_v1 on public.sports as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy sports_public_active_select_v1 on public.sports as PERMISSIVE for SELECT to anon, authenticated using (((COALESCE(is_active, true) IS TRUE) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy sports_db_closed_deny_v79 on public.sports_db as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy "Lecture news publique" on public.system_news as PERMISSIVE for SELECT to authenticated using (true);
create policy "Public Read News" on public.system_news as PERMISSIVE for SELECT to public using (true);
create policy system_news_admin_all_v79 on public.system_news as PERMISSIVE for ALL to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy "Public Read Talents" on public.talents as PERMISSIVE for SELECT to public using (true);
create policy game_data_public_read_talents on public.talents as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy titan_catalog_public_read on public.talents as PERMISSIVE for SELECT to anon, authenticated using (true);
create policy titan_audit_read_admin on public.titan_admin_audit as PERMISSIVE for SELECT to authenticated using (titan_is_admin(( SELECT auth.uid() AS uid)));
create policy titan_admins_read_self_or_admin on public.titan_admins as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR titan_is_admin(( SELECT auth.uid() AS uid))));
create policy titan_billing_events_closed_deny_v79 on public.titan_billing_events as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy cache_reconciliation_select_own_or_admin on public.titan_cache_reconciliation_reports as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR titan_is_admin(( SELECT auth.uid() AS uid))));
create policy titan_reports_insert_authenticated on public.titan_moderation_reports as PERMISSIVE for INSERT to authenticated with check ((reporter_id = ( SELECT auth.uid() AS uid)));
create policy titan_reports_select_admin_or_own on public.titan_moderation_reports as PERMISSIVE for SELECT to authenticated using (((reporter_id = ( SELECT auth.uid() AS uid)) OR titan_is_admin(( SELECT auth.uid() AS uid))));
create policy titan_public_stats_cache_read on public.titan_public_stats_cache as PERMISSIVE for SELECT to anon, authenticated using ((key = 'partnership'::text));
create policy titan_social_action_log_closed_deny_v79 on public.titan_social_action_log as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy titan_suspicious_select_own_or_admin on public.titan_suspicious_actions as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR titan_is_admin(( SELECT auth.uid() AS uid))));
create policy titan_blocks_delete_own on public.titan_user_blocks as PERMISSIVE for DELETE to authenticated using ((blocker_id = ( SELECT auth.uid() AS uid)));
create policy titan_blocks_insert_own on public.titan_user_blocks as PERMISSIVE for INSERT to authenticated with check ((blocker_id = ( SELECT auth.uid() AS uid)));
create policy titan_blocks_select_own on public.titan_user_blocks as PERMISSIVE for SELECT to authenticated using (((blocker_id = ( SELECT auth.uid() AS uid)) OR (blocked_id = ( SELECT auth.uid() AS uid))));
create policy titan_weekly_reward_usage_closed_deny_v79 on public.titan_weekly_reward_usage as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
create policy training_logs_admin_update_v1 on public.training_logs as PERMISSIVE for UPDATE to authenticated using (private.titan_is_admin(( SELECT auth.uid() AS uid))) with check (private.titan_is_admin(( SELECT auth.uid() AS uid)));
create policy training_logs_self_or_admin_select_v1 on public.training_logs as PERMISSIVE for SELECT to authenticated using (((user_id = ( SELECT auth.uid() AS uid)) OR private.titan_is_admin(( SELECT auth.uid() AS uid))));
create policy user_achievements_own_all on public.user_achievements as PERMISSIVE for ALL to authenticated using ((user_id = ( SELECT auth.uid() AS uid))) with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy user_achievements_own_select on public.user_achievements as PERMISSIVE for SELECT to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy user_bestiary_select_own on public.user_bestiary as PERMISSIVE for SELECT to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy weekly_quests_public_read on public.weekly_quests as PERMISSIVE for SELECT to anon, authenticated using (((is_active = true) AND ((active_to IS NULL) OR (active_to >= now()))));
create policy zones_closed_deny_v79 on public.zones as RESTRICTIVE for ALL to anon, authenticated using (false) with check (false);
-- table grants
grant SELECT on public.achievements_config to anon;
grant SELECT on public.achievements_config to authenticated;
grant INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.achievements_config to service_role;
grant SELECT, INSERT on public.admin_logs to authenticated;
grant REFERENCES, INSERT, SELECT, UPDATE, DELETE, TRUNCATE, TRIGGER on public.admin_logs to service_role;
grant SELECT, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE on public.admin_messages to service_role;
grant SELECT, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE on public.admin_whitelist to service_role;
grant SELECT on public.adventure_profiles to authenticated;
grant SELECT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, INSERT on public.adventure_profiles to service_role;
grant SELECT on public.adventure_progress to authenticated;
grant TRUNCATE, TRIGGER, INSERT, SELECT, UPDATE, DELETE, REFERENCES on public.adventure_progress to service_role;
grant SELECT on public.adventure_rewards to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.adventure_rewards to service_role;
grant SELECT on public.adventure_worlds to anon;
grant SELECT on public.adventure_worlds to authenticated;
grant SELECT, UPDATE, TRIGGER, DELETE, INSERT, TRUNCATE, REFERENCES on public.adventure_worlds to service_role;
grant SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, INSERT on public.analytics_events to anon;
grant UPDATE, INSERT, SELECT, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.analytics_events to authenticated;
grant SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, INSERT on public.analytics_events to service_role;
grant SELECT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, INSERT on public.announcements to anon;
grant DELETE, TRIGGER, TRUNCATE, UPDATE, REFERENCES, INSERT, SELECT on public.announcements to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.announcements to service_role;
grant SELECT, TRIGGER, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES on public.audit_logs to service_role;
grant SELECT on public.bosses to anon;
grant DELETE, UPDATE, INSERT, SELECT on public.bosses to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.bosses to service_role;
grant INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.bug_reports to anon;
grant REFERENCES, TRIGGER, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.bug_reports to authenticated;
grant SELECT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, INSERT on public.bug_reports to service_role;
grant SELECT, INSERT, REFERENCES, TRUNCATE, DELETE, UPDATE, TRIGGER on public.campaign_state to service_role;
grant SELECT on public.coach_assignments to authenticated;
grant SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, INSERT on public.coach_assignments to service_role;
grant SELECT on public.coach_links to authenticated;
grant TRUNCATE, TRIGGER, REFERENCES, DELETE, UPDATE, SELECT, INSERT on public.coach_links to service_role;
grant SELECT on public.combat_logs to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.combat_logs to service_role;
grant INSERT on public.contact_messages to anon;
grant DELETE, UPDATE, SELECT, INSERT on public.contact_messages to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, TRIGGER, REFERENCES on public.contact_messages to service_role;
grant REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, TRIGGER, INSERT on public.content_blocks to anon;
grant INSERT, DELETE, TRUNCATE, TRIGGER, REFERENCES, UPDATE, SELECT on public.content_blocks to authenticated;
grant TRUNCATE, TRIGGER, REFERENCES, INSERT, DELETE, UPDATE, SELECT on public.content_blocks to service_role;
grant UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, INSERT, SELECT on public.contest_draws to anon;
grant INSERT, TRUNCATE, REFERENCES, TRIGGER, DELETE, UPDATE, SELECT on public.contest_draws to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.contest_draws to service_role;
grant SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.contest_entries to anon;
grant UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, INSERT, SELECT on public.contest_entries to authenticated;
grant INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.contest_entries to service_role;
grant TRIGGER, INSERT, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.coupons to service_role;
grant DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, INSERT, SELECT on public.creatures to anon;
grant DELETE, INSERT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, SELECT on public.creatures to authenticated;
grant REFERENCES, TRIGGER, INSERT, SELECT, UPDATE, DELETE, TRUNCATE on public.creatures to service_role;
grant SELECT, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE on public.daily_quests to service_role;
grant UPDATE, TRIGGER, REFERENCES, TRUNCATE, DELETE, INSERT, SELECT on public.dynamic_pages to anon;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, INSERT, SELECT, UPDATE on public.dynamic_pages to authenticated;
grant INSERT, REFERENCES, TRIGGER, TRUNCATE, DELETE, UPDATE, SELECT on public.dynamic_pages to service_role;
grant SELECT on public.dynamic_quests to anon;
grant SELECT on public.dynamic_quests to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.dynamic_quests to service_role;
grant INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.friends to service_role;
grant DELETE, SELECT, INSERT on public.friendships to authenticated;
grant INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.friendships to service_role;
grant SELECT on public.fun_stats to anon;
grant SELECT on public.fun_stats to authenticated;
grant UPDATE, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, SELECT on public.fun_stats to service_role;
grant TRIGGER, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, INSERT on public.game_settings to service_role;
grant SELECT on public.global_config to anon;
grant SELECT on public.global_config to authenticated;
grant SELECT, REFERENCES, TRUNCATE, DELETE, UPDATE, INSERT, TRIGGER on public.global_config to service_role;
grant SELECT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, INSERT on public.guild_members to authenticated;
grant INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.guild_members to service_role;
grant REFERENCES, SELECT, TRUNCATE, TRIGGER on public.guild_messages to authenticated;
grant REFERENCES, TRUNCATE, DELETE, INSERT, UPDATE, SELECT, TRIGGER on public.guild_messages to service_role;
grant UPDATE, INSERT, SELECT on public.guild_raid to authenticated;
grant DELETE, INSERT, SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER on public.guild_raid to service_role;
grant SELECT, UPDATE, INSERT on public.guilds to authenticated;
grant DELETE, REFERENCES, TRUNCATE, TRIGGER, INSERT, SELECT, UPDATE on public.guilds to service_role;
grant REFERENCES, UPDATE, DELETE, TRIGGER, INSERT, TRUNCATE, SELECT on public.influencers to anon;
grant TRUNCATE, INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER on public.influencers to authenticated;
grant SELECT, UPDATE, DELETE, INSERT, TRUNCATE, REFERENCES, TRIGGER on public.influencers to service_role;
grant SELECT on public.inventory to authenticated;
grant DELETE, INSERT, SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER on public.inventory to service_role;
grant SELECT on public.items to anon;
grant SELECT on public.items to authenticated;
grant SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, INSERT on public.items to service_role;
grant TRUNCATE, INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER on public.lore_chapters to anon;
grant TRUNCATE, UPDATE, SELECT, INSERT, TRIGGER, REFERENCES, DELETE on public.lore_chapters to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.lore_chapters to service_role;
grant SELECT on public.messages to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.messages to service_role;
grant SELECT on public.mobs to anon;
grant DELETE, UPDATE, INSERT, SELECT on public.mobs to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.mobs to service_role;
grant SELECT on public.news_updates to anon;
grant SELECT on public.news_updates to authenticated;
grant TRIGGER, INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES on public.news_updates to service_role;
grant INSERT, SELECT, TRUNCATE, REFERENCES, TRIGGER, DELETE, UPDATE on public.premium_access to anon;
grant DELETE, INSERT, SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER on public.premium_access to authenticated;
grant TRIGGER, INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES on public.premium_access to service_role;
grant SELECT, UPDATE on public.profiles to authenticated;
grant INSERT, REFERENCES, TRUNCATE, DELETE, UPDATE, TRIGGER, SELECT on public.profiles to service_role;
grant UPDATE, INSERT, SELECT, REFERENCES, TRUNCATE, DELETE, TRIGGER on public.referrals to anon;
grant TRUNCATE, DELETE, INSERT, SELECT, UPDATE, REFERENCES, TRIGGER on public.referrals to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.referrals to service_role;
grant INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT on public.reports to service_role;
grant INSERT, SELECT on public.shop_history to authenticated;
grant UPDATE, TRIGGER, REFERENCES, TRUNCATE, DELETE, SELECT, INSERT on public.shop_history to service_role;
grant SELECT on public.shop_items to anon;
grant UPDATE, DELETE, INSERT, SELECT on public.shop_items to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.shop_items to service_role;
grant DELETE, TRIGGER, TRUNCATE, SELECT, UPDATE, REFERENCES, INSERT on public.site_settings to anon;
grant SELECT, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE on public.site_settings to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.site_settings to service_role;
grant SELECT on public.social_challenges to authenticated;
grant REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT, TRIGGER on public.social_challenges to service_role;
grant INSERT, SELECT, UPDATE on public.sport_goals to authenticated;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, SELECT on public.sport_goals to service_role;
grant SELECT on public.sports to anon;
grant DELETE, UPDATE, SELECT, INSERT on public.sports to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.sports to service_role;
grant TRIGGER, INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES on public.sports_db to service_role;
grant SELECT on public.system_news to anon;
grant SELECT on public.system_news to authenticated;
grant TRIGGER, REFERENCES, TRUNCATE, INSERT, DELETE, UPDATE, SELECT on public.system_news to service_role;
grant SELECT on public.talents to anon;
grant SELECT on public.talents to authenticated;
grant DELETE, TRIGGER, REFERENCES, TRUNCATE, UPDATE, SELECT, INSERT on public.talents to service_role;
grant SELECT on public.titan_admin_audit to authenticated;
grant SELECT, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE on public.titan_admin_audit to service_role;
grant SELECT on public.titan_admins to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.titan_admins to service_role;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.titan_billing_events to service_role;
grant SELECT on public.titan_cache_reconciliation_reports to authenticated;
grant SELECT, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE on public.titan_cache_reconciliation_reports to service_role;
grant SELECT, INSERT on public.titan_moderation_reports to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.titan_moderation_reports to service_role;
grant TRUNCATE, UPDATE, SELECT, DELETE, TRIGGER, REFERENCES, INSERT on public.titan_public_stats_cache to anon;
grant DELETE, SELECT, UPDATE, REFERENCES, TRUNCATE, TRIGGER, INSERT on public.titan_public_stats_cache to authenticated;
grant SELECT, INSERT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE on public.titan_public_stats_cache to service_role;
grant SELECT, UPDATE, INSERT, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.titan_social_action_log to service_role;
grant SELECT on public.titan_suspicious_actions to authenticated;
grant DELETE, SELECT, UPDATE, TRUNCATE, REFERENCES, TRIGGER, INSERT on public.titan_suspicious_actions to service_role;
grant TRIGGER, REFERENCES, TRUNCATE, INSERT, DELETE, SELECT, UPDATE on public.titan_user_blocks to service_role;
grant TRUNCATE, INSERT, SELECT, UPDATE, DELETE, REFERENCES, TRIGGER on public.titan_weekly_reward_usage to service_role;
grant UPDATE, SELECT on public.training_logs to authenticated;
grant SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, INSERT on public.training_logs to service_role;
grant TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.training_receipts to service_role;
grant SELECT, TRIGGER, REFERENCES, TRUNCATE, DELETE, UPDATE, INSERT on public.training_revisions to service_role;
grant SELECT on public.user_achievements to authenticated;
grant REFERENCES, TRIGGER, TRUNCATE, DELETE, UPDATE, SELECT, INSERT on public.user_achievements to service_role;
grant SELECT on public.user_bestiary to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.user_bestiary to service_role;
grant SELECT on public.weekly_quests to anon;
grant SELECT on public.weekly_quests to authenticated;
grant TRIGGER, INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES on public.weekly_quests to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER on public.zones to service_role;
-- function grants (revoke defaults first)
revoke all on function add_friend_by_code(text) from public, anon, authenticated;
revoke all on function add_friend_by_id(uuid) from public, anon, authenticated;
revoke all on function add_rewards(uuid,integer,integer) from public, anon, authenticated;
revoke all on function check_auth_user() from public, anon, authenticated;
revoke all on function check_if_admin() from public, anon, authenticated;
revoke all on function delete_inactive_users() from public, anon, authenticated;
revoke all on function delete_own_account() from public, anon, authenticated;
revoke all on function export_own_data() from public, anon, authenticated;
revoke all on function get_my_friends_v2() from public, anon, authenticated;
revoke all on function get_server_date() from public, anon, authenticated;
revoke all on function handle_audit_log() from public, anon, authenticated;
revoke all on function handle_new_user() from public, anon, authenticated;
revoke all on function is_admin() from public, anon, authenticated;
revoke all on function is_super_admin() from public, anon, authenticated;
revoke all on function private.titan_admin_assert() from public, anon, authenticated;
revoke all on function private.titan_admin_dashboard_v1() from public, anon, authenticated;
revoke all on function private.titan_admin_get_context_v1() from public, anon, authenticated;
revoke all on function private.titan_admin_grant_premium_v1(uuid,text,text,timestamp with time zone,boolean,text) from public, anon, authenticated;
revoke all on function private.titan_admin_list_profiles_v1(text,text,text,text,integer,integer) from public, anon, authenticated;
revoke all on function private.titan_admin_log_v1(text,text,text,jsonb,jsonb,text) from public, anon, authenticated;
revoke all on function private.titan_admin_revoke_premium_v1(uuid,text) from public, anon, authenticated;
revoke all on function private.titan_admin_role_for(uuid) from public, anon, authenticated;
revoke all on function private.titan_admin_run_contest_draw_v1(text,text) from public, anon, authenticated;
revoke all on function private.titan_admin_update_profile_v1(uuid,jsonb,text) from public, anon, authenticated;
revoke all on function private.titan_admin_upsert_row_v1(text,text,jsonb,text) from public, anon, authenticated;
revoke all on function private.titan_adventure_action(text,text,text,text,integer,integer,text) from public, anon, authenticated;
revoke all on function private.titan_coach_portal(text,jsonb) from public, anon, authenticated;
revoke all on function private.titan_guard_billing_fields() from public, anon, authenticated;
revoke all on function private.titan_guard_profile_privileges() from public, anon, authenticated;
revoke all on function private.titan_guard_sport_goal() from public, anon, authenticated;
revoke all on function private.titan_is_admin(uuid) from public, anon, authenticated;
revoke all on function private.titan_is_moderator_or_admin(uuid) from public, anon, authenticated;
revoke all on function private.titan_progression_snapshot_v78() from public, anon, authenticated;
revoke all on function private.titan_update_training_session(uuid,integer,jsonb) from public, anon, authenticated;
revoke all on function purchase_lootbox() from public, anon, authenticated;
revoke all on function submit_activity(text,jsonb) from public, anon, authenticated;
revoke all on function titan_add_friend_by_code(text) from public, anon, authenticated;
revoke all on function titan_admin_allowed_content_tables() from public, anon, authenticated;
revoke all on function titan_admin_assert() from public, anon, authenticated;
revoke all on function titan_admin_audit_write(text,uuid,jsonb) from public, anon, authenticated;
revoke all on function titan_admin_claim_first(text) from public, anon, authenticated;
revoke all on function titan_admin_content_catalog() from public, anon, authenticated;
revoke all on function titan_admin_dashboard_v1() from public, anon, authenticated;
revoke all on function titan_admin_dashboard() from public, anon, authenticated;
revoke all on function titan_admin_delete_content(text,text) from public, anon, authenticated;
revoke all on function titan_admin_delete_message(text) from public, anon, authenticated;
revoke all on function titan_admin_get_context_v1() from public, anon, authenticated;
revoke all on function titan_admin_grant_premium_v1(uuid,text,text,timestamp with time zone,boolean,text) from public, anon, authenticated;
revoke all on function titan_admin_hide_chat_message(text,text) from public, anon, authenticated;
revoke all on function titan_admin_json_value_sql(jsonb,text,text) from public, anon, authenticated;
revoke all on function titan_admin_list_content(text,integer) from public, anon, authenticated;
revoke all on function titan_admin_list_messages(integer) from public, anon, authenticated;
revoke all on function titan_admin_list_news(integer) from public, anon, authenticated;
revoke all on function titan_admin_list_profiles_v1(text,text,text,text,integer,integer) from public, anon, authenticated;
revoke all on function titan_admin_list_profiles(text,integer,integer) from public, anon, authenticated;
revoke all on function titan_admin_list_reports(text,integer) from public, anon, authenticated;
revoke all on function titan_admin_publish_news(text,text,text,text,boolean) from public, anon, authenticated;
revoke all on function titan_admin_resolve_report(uuid,text,text) from public, anon, authenticated;
revoke all on function titan_admin_revoke_premium_v1(uuid,text) from public, anon, authenticated;
revoke all on function titan_admin_role(uuid) from public, anon, authenticated;
revoke all on function titan_admin_run_contest_draw_v1(text,text) from public, anon, authenticated;
revoke all on function titan_admin_set_news_active(uuid,boolean) from public, anon, authenticated;
revoke all on function titan_admin_update_profile_v1(uuid,jsonb,text) from public, anon, authenticated;
revoke all on function titan_admin_update_profile(uuid,jsonb) from public, anon, authenticated;
revoke all on function titan_admin_upsert_content(text,jsonb) from public, anon, authenticated;
revoke all on function titan_admin_upsert_row_v1(text,text,jsonb,text) from public, anon, authenticated;
revoke all on function titan_admin_write_log_v1(text,text,text,jsonb,jsonb,text) from public, anon, authenticated;
revoke all on function titan_adventure_action(text,text,text,text,integer,integer,text) from public, anon, authenticated;
revoke all on function titan_adventure_evidence(text) from public, anon, authenticated;
revoke all on function titan_adventure_snapshot() from public, anon, authenticated;
revoke all on function titan_apply_paddle_entitlement_v87(uuid,boolean,text,text,timestamp with time zone,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone) from public, anon, authenticated;
revoke all on function titan_apply_progression_reward(uuid,integer,integer) from public, anon, authenticated;
revoke all on function titan_apply_weekly_reward_cap(uuid,integer,integer) from public, anon, authenticated;
revoke all on function titan_assign_friend_code() from public, anon, authenticated;
revoke all on function titan_block_user(uuid,text) from public, anon, authenticated;
revoke all on function titan_cache_safe_int(text,integer) from public, anon, authenticated;
revoke all on function titan_cache_safe_timestamptz(text) from public, anon, authenticated;
revoke all on function titan_charge_credits(uuid,integer,text) from public, anon, authenticated;
revoke all on function titan_claim_achievement(text) from public, anon, authenticated;
revoke all on function titan_clean_economy_message(text,integer) from public, anon, authenticated;
revoke all on function titan_clean_social_text(text,text,integer) from public, anon, authenticated;
revoke all on function titan_clean_state_username(text) from public, anon, authenticated;
revoke all on function titan_coach_portal(text,jsonb) from public, anon, authenticated;
revoke all on function titan_create_guild(text,text) from public, anon, authenticated;
revoke all on function titan_create_social_challenge(uuid,text,numeric) from public, anon, authenticated;
revoke all on function titan_create_wager_challenge(uuid,text,integer) from public, anon, authenticated;
revoke all on function titan_delete_rows(text,text,uuid) from public, anon, authenticated;
revoke all on function titan_economy_limits(uuid) from public, anon, authenticated;
revoke all on function titan_export_rows(text,text,uuid) from public, anon, authenticated;
revoke all on function titan_find_profile_by_friend_code(text) from public, anon, authenticated;
revoke all on function titan_generate_friend_code() from public, anon, authenticated;
revoke all on function titan_generate_guild_code() from public, anon, authenticated;
revoke all on function titan_get_economy_status() from public, anon, authenticated;
revoke all on function titan_get_my_guild() from public, anon, authenticated;
revoke all on function titan_get_progression_snapshot() from public, anon, authenticated;
revoke all on function titan_guard_friendship_delete() from public, anon, authenticated;
revoke all on function titan_guard_friendship_insert() from public, anon, authenticated;
revoke all on function titan_guard_message_insert() from public, anon, authenticated;
revoke all on function titan_guard_profile_progression() from public, anon, authenticated;
revoke all on function titan_guard_training_log() from public, anon, authenticated;
revoke all on function titan_is_admin(uuid) from public, anon, authenticated;
revoke all on function titan_join_guild(text) from public, anon, authenticated;
revoke all on function titan_jsonb_array_length_safe(jsonb) from public, anon, authenticated;
revoke all on function titan_jsonb_numeric(jsonb,text) from public, anon, authenticated;
revoke all on function titan_jsonb_object_size_safe(jsonb) from public, anon, authenticated;
revoke all on function titan_leave_guild() from public, anon, authenticated;
revoke all on function titan_level_requirement(integer) from public, anon, authenticated;
revoke all on function titan_list_global_messages() from public, anon, authenticated;
revoke all on function titan_list_guild_messages() from public, anon, authenticated;
revoke all on function titan_list_my_friends() from public, anon, authenticated;
revoke all on function titan_log_suspicious_action(uuid,text,text,text,jsonb) from public, anon, authenticated;
revoke all on function titan_normalize_guild_code(text) from public, anon, authenticated;
revoke all on function titan_numeric_from_json(jsonb,text) from public, anon, authenticated;
revoke all on function titan_public_partnership_stats() from public, anon, authenticated;
revoke all on function titan_public_release_rls_audit() from public, anon, authenticated;
revoke all on function titan_purchase_shop_item(text) from public, anon, authenticated;
revoke all on function titan_purge_expired_social_messages() from public, anon, authenticated;
revoke all on function titan_reject_suspended_user_action() from public, anon, authenticated;
revoke all on function titan_report_chat_message(text,text) from public, anon, authenticated;
revoke all on function titan_save_profile_state(jsonb,text,text,jsonb,jsonb,integer,text,text) from public, anon, authenticated;
revoke all on function titan_send_global_message(text) from public, anon, authenticated;
revoke all on function titan_send_guild_message(text) from public, anon, authenticated;
revoke all on function titan_set_guild_target(integer) from public, anon, authenticated;
revoke all on function titan_social_rate_limit(uuid,text,interval,integer) from public, anon, authenticated;
revoke all on function titan_submit_cache_reconciliation(jsonb) from public, anon, authenticated;
revoke all on function titan_submit_combat_victory(text,text,text,text,integer,numeric,integer,jsonb) from public, anon, authenticated;
revoke all on function titan_submit_training_session(text,text,numeric,text,jsonb,timestamp with time zone) from public, anon, authenticated;
revoke all on function titan_table_has_column(text,text) from public, anon, authenticated;
revoke all on function titan_training_insights(timestamp with time zone,timestamp with time zone,text,text) from public, anon, authenticated;
revoke all on function titan_training_storage_health() from public, anon, authenticated;
revoke all on function titan_transition_social_challenge(uuid,text) from public, anon, authenticated;
revoke all on function titan_unblock_user(uuid) from public, anon, authenticated;
revoke all on function titan_update_training_session(uuid,integer,jsonb) from public, anon, authenticated;
revoke all on function titan_v72_sport_fields(text) from public, anon, authenticated;
revoke all on function titan_v72_sport_profile(text,text,text,text) from public, anon, authenticated;
revoke all on function titan_v72_tracking_summary(text) from public, anon, authenticated;
revoke all on function titan_week_start(timestamp with time zone) from public, anon, authenticated;
grant execute on function add_friend_by_code(text) to service_role;
grant execute on function add_friend_by_id(uuid) to service_role;
grant execute on function add_rewards(uuid,integer,integer) to service_role;
grant execute on function check_auth_user() to service_role;
grant execute on function check_if_admin() to service_role;
grant execute on function delete_inactive_users() to service_role;
grant execute on function delete_own_account() to authenticated;
grant execute on function delete_own_account() to service_role;
grant execute on function export_own_data() to authenticated;
grant execute on function export_own_data() to service_role;
grant execute on function get_my_friends_v2() to service_role;
grant execute on function get_server_date() to service_role;
grant execute on function handle_audit_log() to service_role;
grant execute on function handle_new_user() to service_role;
grant execute on function is_admin() to service_role;
grant execute on function is_super_admin() to service_role;
grant execute on function private.titan_admin_assert() to anon;
grant execute on function private.titan_admin_assert() to authenticated;
grant execute on function private.titan_admin_assert() to service_role;
grant execute on function private.titan_admin_dashboard_v1() to anon;
grant execute on function private.titan_admin_dashboard_v1() to authenticated;
grant execute on function private.titan_admin_dashboard_v1() to service_role;
grant execute on function private.titan_admin_get_context_v1() to anon;
grant execute on function private.titan_admin_get_context_v1() to authenticated;
grant execute on function private.titan_admin_get_context_v1() to service_role;
grant execute on function private.titan_admin_grant_premium_v1(uuid,text,text,timestamp with time zone,boolean,text) to anon;
grant execute on function private.titan_admin_grant_premium_v1(uuid,text,text,timestamp with time zone,boolean,text) to authenticated;
grant execute on function private.titan_admin_grant_premium_v1(uuid,text,text,timestamp with time zone,boolean,text) to service_role;
grant execute on function private.titan_admin_list_profiles_v1(text,text,text,text,integer,integer) to anon;
grant execute on function private.titan_admin_list_profiles_v1(text,text,text,text,integer,integer) to authenticated;
grant execute on function private.titan_admin_list_profiles_v1(text,text,text,text,integer,integer) to service_role;
grant execute on function private.titan_admin_log_v1(text,text,text,jsonb,jsonb,text) to anon;
grant execute on function private.titan_admin_log_v1(text,text,text,jsonb,jsonb,text) to authenticated;
grant execute on function private.titan_admin_log_v1(text,text,text,jsonb,jsonb,text) to service_role;
grant execute on function private.titan_admin_revoke_premium_v1(uuid,text) to anon;
grant execute on function private.titan_admin_revoke_premium_v1(uuid,text) to authenticated;
grant execute on function private.titan_admin_revoke_premium_v1(uuid,text) to service_role;
grant execute on function private.titan_admin_role_for(uuid) to anon;
grant execute on function private.titan_admin_role_for(uuid) to authenticated;
grant execute on function private.titan_admin_role_for(uuid) to service_role;
grant execute on function private.titan_admin_run_contest_draw_v1(text,text) to anon;
grant execute on function private.titan_admin_run_contest_draw_v1(text,text) to authenticated;
grant execute on function private.titan_admin_run_contest_draw_v1(text,text) to service_role;
grant execute on function private.titan_admin_update_profile_v1(uuid,jsonb,text) to anon;
grant execute on function private.titan_admin_update_profile_v1(uuid,jsonb,text) to authenticated;
grant execute on function private.titan_admin_update_profile_v1(uuid,jsonb,text) to service_role;
grant execute on function private.titan_admin_upsert_row_v1(text,text,jsonb,text) to authenticated;
grant execute on function private.titan_adventure_action(text,text,text,text,integer,integer,text) to authenticated;
grant execute on function private.titan_coach_portal(text,jsonb) to authenticated;
grant execute on function private.titan_is_admin(uuid) to anon;
grant execute on function private.titan_is_admin(uuid) to authenticated;
grant execute on function private.titan_is_admin(uuid) to service_role;
grant execute on function private.titan_is_moderator_or_admin(uuid) to anon;
grant execute on function private.titan_is_moderator_or_admin(uuid) to authenticated;
grant execute on function private.titan_is_moderator_or_admin(uuid) to service_role;
grant execute on function private.titan_progression_snapshot_v78() to authenticated;
grant execute on function private.titan_update_training_session(uuid,integer,jsonb) to authenticated;
grant execute on function purchase_lootbox() to service_role;
grant execute on function submit_activity(text,jsonb) to service_role;
grant execute on function titan_add_friend_by_code(text) to authenticated;
grant execute on function titan_add_friend_by_code(text) to service_role;
grant execute on function titan_admin_allowed_content_tables() to service_role;
grant execute on function titan_admin_assert() to service_role;
grant execute on function titan_admin_audit_write(text,uuid,jsonb) to service_role;
grant execute on function titan_admin_claim_first(text) to service_role;
grant execute on function titan_admin_content_catalog() to service_role;
grant execute on function titan_admin_dashboard_v1() to authenticated;
grant execute on function titan_admin_dashboard_v1() to service_role;
grant execute on function titan_admin_dashboard() to service_role;
grant execute on function titan_admin_delete_content(text,text) to service_role;
grant execute on function titan_admin_delete_message(text) to service_role;
grant execute on function titan_admin_get_context_v1() to authenticated;
grant execute on function titan_admin_get_context_v1() to service_role;
grant execute on function titan_admin_grant_premium_v1(uuid,text,text,timestamp with time zone,boolean,text) to authenticated;
grant execute on function titan_admin_grant_premium_v1(uuid,text,text,timestamp with time zone,boolean,text) to service_role;
grant execute on function titan_admin_hide_chat_message(text,text) to service_role;
grant execute on function titan_admin_json_value_sql(jsonb,text,text) to authenticated;
grant execute on function titan_admin_json_value_sql(jsonb,text,text) to service_role;
grant execute on function titan_admin_list_content(text,integer) to service_role;
grant execute on function titan_admin_list_messages(integer) to service_role;
grant execute on function titan_admin_list_news(integer) to service_role;
grant execute on function titan_admin_list_profiles_v1(text,text,text,text,integer,integer) to authenticated;
grant execute on function titan_admin_list_profiles_v1(text,text,text,text,integer,integer) to service_role;
grant execute on function titan_admin_list_profiles(text,integer,integer) to service_role;
grant execute on function titan_admin_list_reports(text,integer) to service_role;
grant execute on function titan_admin_publish_news(text,text,text,text,boolean) to service_role;
grant execute on function titan_admin_resolve_report(uuid,text,text) to service_role;
grant execute on function titan_admin_revoke_premium_v1(uuid,text) to authenticated;
grant execute on function titan_admin_revoke_premium_v1(uuid,text) to service_role;
grant execute on function titan_admin_role(uuid) to authenticated;
grant execute on function titan_admin_role(uuid) to service_role;
grant execute on function titan_admin_run_contest_draw_v1(text,text) to authenticated;
grant execute on function titan_admin_run_contest_draw_v1(text,text) to service_role;
grant execute on function titan_admin_set_news_active(uuid,boolean) to service_role;
grant execute on function titan_admin_update_profile_v1(uuid,jsonb,text) to authenticated;
grant execute on function titan_admin_update_profile_v1(uuid,jsonb,text) to service_role;
grant execute on function titan_admin_update_profile(uuid,jsonb) to service_role;
grant execute on function titan_admin_upsert_content(text,jsonb) to service_role;
grant execute on function titan_admin_upsert_row_v1(text,text,jsonb,text) to authenticated;
grant execute on function titan_admin_upsert_row_v1(text,text,jsonb,text) to service_role;
grant execute on function titan_admin_write_log_v1(text,text,text,jsonb,jsonb,text) to authenticated;
grant execute on function titan_admin_write_log_v1(text,text,text,jsonb,jsonb,text) to service_role;
grant execute on function titan_adventure_action(text,text,text,text,integer,integer,text) to authenticated;
grant execute on function titan_adventure_action(text,text,text,text,integer,integer,text) to service_role;
grant execute on function titan_adventure_evidence(text) to authenticated;
grant execute on function titan_adventure_evidence(text) to service_role;
grant execute on function titan_adventure_snapshot() to authenticated;
grant execute on function titan_adventure_snapshot() to service_role;
grant execute on function titan_apply_paddle_entitlement_v87(uuid,boolean,text,text,timestamp with time zone,text,text,text,text,timestamp with time zone,timestamp with time zone,timestamp with time zone,timestamp with time zone) to service_role;
grant execute on function titan_apply_progression_reward(uuid,integer,integer) to service_role;
grant execute on function titan_apply_weekly_reward_cap(uuid,integer,integer) to service_role;
grant execute on function titan_assign_friend_code() to authenticated;
grant execute on function titan_assign_friend_code() to service_role;
grant execute on function titan_block_user(uuid,text) to authenticated;
grant execute on function titan_block_user(uuid,text) to service_role;
grant execute on function titan_cache_safe_int(text,integer) to anon;
grant execute on function titan_cache_safe_int(text,integer) to authenticated;
grant execute on function titan_cache_safe_int(text,integer) to service_role;
grant execute on function titan_cache_safe_timestamptz(text) to anon;
grant execute on function titan_cache_safe_timestamptz(text) to authenticated;
grant execute on function titan_cache_safe_timestamptz(text) to service_role;
grant execute on function titan_charge_credits(uuid,integer,text) to service_role;
grant execute on function titan_claim_achievement(text) to authenticated;
grant execute on function titan_claim_achievement(text) to service_role;
grant execute on function titan_clean_economy_message(text,integer) to anon;
grant execute on function titan_clean_economy_message(text,integer) to authenticated;
grant execute on function titan_clean_economy_message(text,integer) to service_role;
grant execute on function titan_clean_social_text(text,text,integer) to service_role;
grant execute on function titan_clean_state_username(text) to service_role;
grant execute on function titan_coach_portal(text,jsonb) to authenticated;
grant execute on function titan_coach_portal(text,jsonb) to service_role;
grant execute on function titan_create_guild(text,text) to authenticated;
grant execute on function titan_create_guild(text,text) to service_role;
grant execute on function titan_create_social_challenge(uuid,text,numeric) to authenticated;
grant execute on function titan_create_social_challenge(uuid,text,numeric) to service_role;
grant execute on function titan_create_wager_challenge(uuid,text,integer) to service_role;
grant execute on function titan_delete_rows(text,text,uuid) to service_role;
grant execute on function titan_economy_limits(uuid) to authenticated;
grant execute on function titan_economy_limits(uuid) to service_role;
grant execute on function titan_export_rows(text,text,uuid) to service_role;
grant execute on function titan_find_profile_by_friend_code(text) to authenticated;
grant execute on function titan_find_profile_by_friend_code(text) to service_role;
grant execute on function titan_generate_friend_code() to service_role;
grant execute on function titan_generate_guild_code() to service_role;
grant execute on function titan_get_economy_status() to service_role;
grant execute on function titan_get_my_guild() to authenticated;
grant execute on function titan_get_my_guild() to service_role;
grant execute on function titan_get_progression_snapshot() to authenticated;
grant execute on function titan_get_progression_snapshot() to service_role;
grant execute on function titan_guard_friendship_delete() to service_role;
grant execute on function titan_guard_friendship_insert() to service_role;
grant execute on function titan_guard_message_insert() to service_role;
grant execute on function titan_guard_profile_progression() to service_role;
grant execute on function titan_guard_training_log() to service_role;
grant execute on function titan_is_admin(uuid) to authenticated;
grant execute on function titan_is_admin(uuid) to service_role;
grant execute on function titan_join_guild(text) to authenticated;
grant execute on function titan_join_guild(text) to service_role;
grant execute on function titan_jsonb_array_length_safe(jsonb) to anon;
grant execute on function titan_jsonb_array_length_safe(jsonb) to authenticated;
grant execute on function titan_jsonb_array_length_safe(jsonb) to service_role;
grant execute on function titan_jsonb_numeric(jsonb,text) to anon;
grant execute on function titan_jsonb_numeric(jsonb,text) to authenticated;
grant execute on function titan_jsonb_numeric(jsonb,text) to service_role;
grant execute on function titan_jsonb_object_size_safe(jsonb) to anon;
grant execute on function titan_jsonb_object_size_safe(jsonb) to authenticated;
grant execute on function titan_jsonb_object_size_safe(jsonb) to service_role;
grant execute on function titan_leave_guild() to authenticated;
grant execute on function titan_leave_guild() to service_role;
grant execute on function titan_level_requirement(integer) to anon;
grant execute on function titan_level_requirement(integer) to authenticated;
grant execute on function titan_level_requirement(integer) to service_role;
grant execute on function titan_list_global_messages() to authenticated;
grant execute on function titan_list_global_messages() to service_role;
grant execute on function titan_list_guild_messages() to authenticated;
grant execute on function titan_list_guild_messages() to service_role;
grant execute on function titan_list_my_friends() to authenticated;
grant execute on function titan_list_my_friends() to service_role;
grant execute on function titan_log_suspicious_action(uuid,text,text,text,jsonb) to service_role;
grant execute on function titan_normalize_guild_code(text) to service_role;
grant execute on function titan_numeric_from_json(jsonb,text) to anon;
grant execute on function titan_numeric_from_json(jsonb,text) to authenticated;
grant execute on function titan_numeric_from_json(jsonb,text) to service_role;
grant execute on function titan_public_partnership_stats() to anon;
grant execute on function titan_public_partnership_stats() to authenticated;
grant execute on function titan_public_partnership_stats() to service_role;
grant execute on function titan_public_release_rls_audit() to service_role;
grant execute on function titan_purchase_shop_item(text) to authenticated;
grant execute on function titan_purchase_shop_item(text) to service_role;
grant execute on function titan_purge_expired_social_messages() to service_role;
grant execute on function titan_reject_suspended_user_action() to service_role;
grant execute on function titan_report_chat_message(text,text) to authenticated;
grant execute on function titan_report_chat_message(text,text) to service_role;
grant execute on function titan_save_profile_state(jsonb,text,text,jsonb,jsonb,integer,text,text) to authenticated;
grant execute on function titan_save_profile_state(jsonb,text,text,jsonb,jsonb,integer,text,text) to service_role;
grant execute on function titan_send_global_message(text) to authenticated;
grant execute on function titan_send_global_message(text) to service_role;
grant execute on function titan_send_guild_message(text) to authenticated;
grant execute on function titan_send_guild_message(text) to service_role;
grant execute on function titan_set_guild_target(integer) to authenticated;
grant execute on function titan_set_guild_target(integer) to service_role;
grant execute on function titan_social_rate_limit(uuid,text,interval,integer) to service_role;
grant execute on function titan_submit_cache_reconciliation(jsonb) to authenticated;
grant execute on function titan_submit_cache_reconciliation(jsonb) to service_role;
grant execute on function titan_submit_combat_victory(text,text,text,text,integer,numeric,integer,jsonb) to authenticated;
grant execute on function titan_submit_combat_victory(text,text,text,text,integer,numeric,integer,jsonb) to service_role;
grant execute on function titan_submit_training_session(text,text,numeric,text,jsonb,timestamp with time zone) to authenticated;
grant execute on function titan_submit_training_session(text,text,numeric,text,jsonb,timestamp with time zone) to service_role;
grant execute on function titan_table_has_column(text,text) to service_role;
grant execute on function titan_training_insights(timestamp with time zone,timestamp with time zone,text,text) to authenticated;
grant execute on function titan_training_insights(timestamp with time zone,timestamp with time zone,text,text) to service_role;
grant execute on function titan_training_storage_health() to service_role;
grant execute on function titan_transition_social_challenge(uuid,text) to authenticated;
grant execute on function titan_transition_social_challenge(uuid,text) to service_role;
grant execute on function titan_unblock_user(uuid) to authenticated;
grant execute on function titan_unblock_user(uuid) to service_role;
grant execute on function titan_update_training_session(uuid,integer,jsonb) to authenticated;
grant execute on function titan_update_training_session(uuid,integer,jsonb) to service_role;
grant execute on function titan_v72_sport_fields(text) to anon;
grant execute on function titan_v72_sport_fields(text) to authenticated;
grant execute on function titan_v72_sport_fields(text) to service_role;
grant execute on function titan_v72_sport_profile(text,text,text,text) to anon;
grant execute on function titan_v72_sport_profile(text,text,text,text) to authenticated;
grant execute on function titan_v72_sport_profile(text,text,text,text) to service_role;
grant execute on function titan_v72_tracking_summary(text) to anon;
grant execute on function titan_v72_tracking_summary(text) to authenticated;
grant execute on function titan_v72_tracking_summary(text) to service_role;
grant execute on function titan_week_start(timestamp with time zone) to anon;
grant execute on function titan_week_start(timestamp with time zone) to authenticated;
grant execute on function titan_week_start(timestamp with time zone) to service_role;
-- schema usage
grant usage on schema private to authenticated;
grant usage on schema public to authenticated;
grant usage on schema public to anon;
grant usage on schema public to service_role;
