-- Reference rows the schema depends on (no user data). Test-only.
insert into public.adventure_worlds(id, tier, chapter_count) values
  ('aube', 'free', 9), ('marees', 'free', 9), ('forge', 'plus', 9), ('aurores', 'plus', 9)
on conflict (id) do nothing;
-- Sports catalog reference rows (id, label, category, unit, balance profile), from tools/data/sports-catalog.json.
insert into public.sports(id, label, category, unit, balance_profile, sort_order) values
('aikido', 'Aïkido', 'combat', 'min', 'combat_grappling', 0),
('alpinism', 'Alpinisme', 'endurance', 'min', 'mountain_endurance', 0),
('bmx', 'BMX / Dirt', 'fun', 'min', 'mtb', 0),
('capoeira', 'Capoeira', 'combat', 'min', 'combat_striking', 0),
('rope_jump', 'Corde à sauter', 'cardio', 'min', 'speed', 0),
('fitness_class', 'Cours Collectif Fitness', 'cardio', 'min', 'mixed_conditioning', 0),
('running', 'Course (Route)', 'cardio', 'km', 'running', 0),
('orienteering', 'Course d Orientation', 'cardio', 'km', 'running', 0),
('hurdles', 'Course de Haies', 'cardio', 'min', 'speed', 0),
('crossfit', 'CrossFit', 'force', 'min', 'mixed_conditioning', 0),
('dips', 'Dips', 'force', 'reps', 'calisthenics', 0),
('climbing', 'Escalade (Mur/Falaise)', 'force', 'm', 'climbing', 0),
('american_football', 'Football Américain', 'team', 'min', 'contact_team', 0),
('powerlifting', 'Force Athlétique', 'force', 'kg', 'strength_max', 0),
('futsal', 'Futsal', 'team', 'min', 'football', 0),
('plank', 'Gainage', 'force', 'min', 'calisthenics', 0),
('gymnastics', 'Gymnastique', 'force', 'min', 'gym_skill', 0),
('bjj', 'Jiu-Jitsu Brésilien', 'combat', 'min', 'combat_grappling', 0),
('karate', 'Karaté', 'combat', 'min', 'combat_striking', 0),
('kendo', 'Kendo', 'combat', 'min', 'combat_weapon', 0),
('kettlebell', 'Kettlebell', 'force', 'kg', 'strength', 0),
('kickboxing', 'Kickboxing', 'combat', 'min', 'combat_striking', 0),
('krav_maga', 'Krav Maga', 'combat', 'min', 'combat_grappling', 0),
('kung_fu', 'Kung Fu', 'combat', 'min', 'combat_grappling', 0),
('lacrosse', 'Lacrosse', 'team', 'min', 'hockey_team', 0),
('walking', 'Marche Active', 'endurance', 'km', 'mountain_endurance', 0),
('farmers_walk', 'Marche du Fermier', 'force', 'm', 'strength', 0),
('nordic_walk', 'Marche Nordique', 'endurance', 'km', 'mountain_endurance', 0),
('mma', 'MMA', 'combat', 'min', 'combat_grappling', 0),
('thaiboxing', 'Muay Thai', 'combat', 'min', 'combat_striking', 0),
('muscu_home', 'Muscu Maison', 'force', 'kg', 'strength', 0),
('muscu_builder', 'Musculation (Builder)', 'muscu', 'kg', 'strength', 0),
('skydiving', 'Parachutisme', 'fun', 'saut', 'skill', 0),
('paragliding', 'Parapente', 'fun', 'min', 'skill', 0),
('parkour', 'Parkour / Free Run', 'force', 'min', 'gym_skill', 0),
('pilates', 'Pilates', 'force', 'min', 'mindbody', 0),
('bodyweight', 'Poids du Corps', 'force', 'reps', 'calisthenics', 0),
('pole_dance', 'Pole Dance', 'force', 'min', 'gym_skill', 0),
('pompes', 'Pompes', 'force', 'reps', 'calisthenics', 0),
('hiking', 'Randonnée', 'endurance', 'km', 'mountain_endurance', 0),
('snowshoeing', 'Raquettes', 'endurance', 'km', 'mountain_endurance', 0),
('roller', 'Roller / Patins', 'endurance', 'km', 'glide', 0),
('rugby', 'Rugby', 'team', 'min', 'rugby', 0),
('sandbag', 'Sac de Sable', 'force', 'min', 'strength', 0),
('muscu_gym', 'Salle de Sport (Fonte)', 'force', 'kg', 'strength', 0),
('savate', 'Savate BF', 'combat', 'min', 'combat_striking', 0),
('abs_session', 'Séance Abdos', 'force', 'min', 'calisthenics', 0),
('spinning', 'Spinning / RPM', 'cardio', 'min', 'cycling', 0),
('sprint', 'Sprint / Fractionné', 'cardio', 'min', 'speed', 0),
('squat', 'Squats (Poids du corps)', 'force', 'reps', 'calisthenics', 0),
('street_workout', 'Street Workout', 'force', 'min', 'calisthenics', 0),
('strongman', 'Strongman', 'force', 'min', 'strength_max', 0),
('treadmill', 'Tapis de Course', 'cardio', 'km', 'running', 0),
('tractions', 'Tractions', 'force', 'reps', 'calisthenics', 0),
('trail', 'Trail / Nature', 'cardio', 'km', 'mountain_endurance', 0),
('trx', 'TRX / Suspension', 'force', 'min', 'strength', 0),
('ultimate', 'Ultimate Frisbee', 'team', 'min', 'hockey_team', 0),
('cycling_indoor', 'Vélo d Appartement', 'endurance', 'km', 'cycling', 0),
('cycling', 'Vélo de Route', 'endurance', 'km', 'cycling', 0),
('elliptical', 'Vélo Elliptique', 'cardio', 'km', 'mixed_conditioning', 0),
('velotaf', 'Vélotaf (Transport)', 'endurance', 'km', 'cycling', 0),
('via_ferrata', 'Via Ferrata', 'endurance', 'min', 'mountain_endurance', 0),
('zumba', 'Zumba', 'cardio', 'min', 'dance', 0),
('padel', 'Padel', 'team', 'min', 'racket', 730),
('dance', 'Danse', 'mobility', 'min', 'skill', 734),
('pickleball', 'Pickleball', 'team', 'min', 'racket', 735),
('gravel', 'Gravel', 'outdoor', 'km', 'cycling', 736),
('ski_touring', 'Ski rando', 'outdoor', 'km', 'glide', 737),
('trekking', 'Randonnee longue', 'outdoor', 'km', 'hiking', 738),
('bouldering', 'Escalade bloc', 'skill', 'min', 'climbing', 739),
('climbing_route', 'Escalade voie', 'skill', 'min', 'climbing', 740),
('rowing_machine', 'Rameur', 'cardio', 'min', 'water', 741),
('kayak', 'Kayak', 'outdoor', 'km', 'water', 742),
('paddle', 'Paddle', 'outdoor', 'km', 'water', 743),
('yoga_mobility', 'Yoga mobilite', 'mobility', 'min', 'mobility', 744),
('hiit', 'HIIT', 'crossfit', 'min', 'mixed', 745),
('hyrox', 'Hyrox', 'crossfit', 'min', 'mixed', 746),
('basketball_3x3', 'Basketball 3x3', 'team', 'min', 'team', 770),
('archery', 'Tir à l arc', 'skill', 'min', 'precision', 771),
('artistic_gymnastics', 'Gym artistique', 'skill', 'min', 'skill', 772),
('artistic_swimming', 'Natation artistique', 'skill', 'min', 'swimming', 773),
('athletics', 'Athletisme', 'cardio', 'min', 'running', 774),
('badminton', 'Badminton', 'cardio', 'min', 'racket', 775),
('baseball', 'Baseball', 'team', 'min', 'team', 776),
('basketball', 'Basketball', 'team', 'min', 'team', 777),
('beach_volleyball', 'Beach volley', 'team', 'min', 'team', 778),
('bmx_freestyle', 'BMX freestyle', 'skill', 'min', 'glide', 779),
('bmx_racing', 'BMX racing', 'cardio', 'min', 'cycling', 780),
('boxing', 'Boxe Anglaise', 'combat', 'min', 'combat', 781),
('canoe_slalom', 'Canoe slalom', 'skill', 'min', 'water', 782),
('canoe_sprint', 'Canoe sprint', 'cardio', 'km', 'water', 783),
('sport_climbing', 'Escalade sportive', 'skill', 'min', 'climbing', 784),
('cricket', 'Cricket', 'team', 'min', 'team', 785),
('cycling_road', 'Cyclisme route', 'endurance', 'km', 'cycling', 786),
('cycling_track', 'Cyclisme piste', 'cardio', 'min', 'cycling', 787),
('springboard_diving', 'Plongeon', 'skill', 'min', 'skill', 788),
('equestrian', 'Equitation', 'skill', 'min', 'skill', 789),
('fencing', 'Escrime', 'combat', 'min', 'combat', 790),
('flag_football', 'Flag football', 'team', 'min', 'team', 791),
('football', 'Football', 'team', 'min', 'football', 792),
('golf', 'Golf', 'skill', 'min', 'precision', 793),
('handball', 'Handball', 'team', 'min', 'team', 794),
('field_hockey', 'Hockey sur gazon', 'team', 'min', 'team', 795),
('judo', 'Judo', 'combat', 'min', 'combat', 796),
('lacrosse_sixes', 'Lacrosse sixes', 'team', 'min', 'team', 797),
('modern_pentathlon', 'Pentathlon moderne', 'mixed', 'min', 'mixed', 798),
('mountain_bike', 'VTT', 'outdoor', 'km', 'cycling', 799),
('open_water_swimming', 'Nage eau libre', 'endurance', 'm', 'swimming', 800),
('rhythmic_gymnastics', 'Gym rythmique', 'skill', 'min', 'skill', 801),
('rowing', 'Aviron', 'endurance', 'km', 'water', 802),
('coastal_rowing', 'Aviron coastal', 'outdoor', 'km', 'water', 803),
('rugby_sevens', 'Rugby a 7', 'team', 'min', 'team', 804),
('sailing', 'Voile', 'skill', 'min', 'water', 805),
('shooting', 'Tir sportif', 'skill', 'min', 'precision', 806),
('skateboarding', 'Skateboard', 'skill', 'min', 'glide', 807),
('softball', 'Softball', 'team', 'min', 'team', 808),
('squash', 'Squash', 'cardio', 'min', 'racket', 809),
('surfing', 'Surf', 'skill', 'min', 'water', 810),
('swimming', 'Natation (Piscine)', 'endurance', 'm', 'swimming', 811),
('table_tennis', 'Ping-Pong', 'cardio', 'min', 'racket', 812),
('taekwondo', 'Taekwondo', 'combat', 'min', 'combat', 813),
('tennis', 'Tennis', 'cardio', 'min', 'racket', 814),
('trampoline_gymnastics', 'Trampoline', 'skill', 'min', 'skill', 815),
('triathlon', 'Triathlon', 'endurance', 'km', 'mixed', 816),
('volleyball', 'Volleyball', 'team', 'min', 'team', 817),
('water_polo', 'Water Polo', 'team', 'min', 'team', 818),
('weightlifting', 'Halterophilie', 'force', 'kg', 'strength', 819),
('wrestling', 'Lutte', 'combat', 'min', 'combat', 820),
('alpine_skiing', 'Ski alpin', 'outdoor', 'km', 'glide', 830),
('biathlon', 'Biathlon', 'outdoor', 'km', 'glide', 831),
('bobsleigh', 'Bobsleigh', 'skill', 'min', 'glide', 832),
('cross_country_skiing', 'Ski de fond', 'outdoor', 'km', 'glide', 833),
('curling', 'Curling', 'skill', 'min', 'precision', 834),
('figure_skating', 'Patinage artistique', 'skill', 'min', 'glide', 835),
('freestyle_skiing', 'Ski freestyle', 'skill', 'min', 'glide', 836),
('ice_hockey', 'Hockey sur glace', 'team', 'min', 'team', 837),
('luge', 'Luge', 'skill', 'min', 'glide', 838),
('nordic_combined', 'Combine nordique', 'outdoor', 'km', 'glide', 839),
('short_track_speed_skating', 'Short track', 'cardio', 'min', 'glide', 840),
('skeleton', 'Skeleton', 'skill', 'min', 'glide', 841),
('ski_jumping', 'Saut a ski', 'skill', 'min', 'glide', 842),
('ski_mountaineering', 'Ski alpinisme', 'outdoor', 'km', 'glide', 843),
('snowboard', 'Snowboard', 'outdoor', 'km', 'glide', 844),
('speed_skating', 'Patinage de vitesse', 'cardio', 'min', 'glide', 845),
('duathlon', 'Duathlon', 'endurance', 'km', 'mixed', 900),
('aquathlon', 'Aquathlon', 'endurance', 'km', 'mixed', 901),
('swimrun', 'Swimrun', 'outdoor', 'km', 'mixed', 902),
('obstacle_course', 'Course obstacles', 'cardio', 'km', 'mixed', 903),
('rucking', 'Rucking', 'outdoor', 'km', 'hiking', 904),
('stair_climbing', 'Montee escaliers', 'cardio', 'min', 'speed', 905),
('handbike', 'Handbike', 'endurance', 'km', 'cycling', 906),
('wheelchair_basketball', 'Basket fauteuil', 'team', 'min', 'team', 907),
('para_swimming', 'Para natation', 'endurance', 'm', 'swimming', 908),
('para_athletics', 'Para athletisme', 'cardio', 'min', 'running', 909),
('dragon_boat', 'Dragon boat', 'team', 'km', 'water', 910),
('netball', 'Netball', 'team', 'min', 'team', 911),
('korfball', 'Korfball', 'team', 'min', 'team', 912),
('floorball', 'Floorball', 'team', 'min', 'team', 913),
('inline_hockey', 'Roller hockey', 'team', 'min', 'team', 914),
('roller_derby', 'Roller derby', 'team', 'min', 'team', 915),
('lifesaving_sport', 'Sauvetage sportif', 'mixed', 'min', 'water', 916),
('freediving', 'Apnee', 'skill', 'min', 'water', 917),
('snorkeling', 'Snorkeling', 'zen', 'min', 'water', 918),
('roller_ski', 'Ski-roues', 'endurance', 'km', 'glide', 919),
('aquagym', 'Aquagym', 'mobility', 'min', 'swimming', 928),
('ballet', 'Danse Classique', 'skill', 'min', 'skill', 1010),
('bowling', 'Bowling', 'skill', 'min', 'precision', 1030),
('canyoning', 'Canyoning', 'outdoor', 'min', 'water', 1040),
('circus', 'Arts du Cirque', 'skill', 'min', 'skill', 1045),
('darts', 'Fléchettes', 'skill', 'min', 'precision', 1050),
('diving', 'Plongée', 'skill', 'min', 'water', 1060),
('hiphop', 'Hip-Hop / Street', 'skill', 'min', 'skill', 1080),
('ice_skating', 'Patinage sur Glace', 'skill', 'min', 'glide', 1090),
('kitesurf', 'Kitesurf', 'outdoor', 'min', 'water', 1100),
('qigong', 'Qi Gong', 'mobility', 'min', 'mobility', 1120),
('salsa', 'Salsa / Latine', 'skill', 'min', 'skill', 1130),
('stretching', 'Stretching', 'mobility', 'min', 'mobility', 1140),
('taichi', 'Tai Chi', 'mobility', 'min', 'mobility', 1150),
('wakeboard', 'Wakeboard', 'outdoor', 'min', 'water', 1160),
('windsurf', 'Planche à Voile', 'outdoor', 'min', 'water', 1170),
('yoga', 'Yoga (Hatha/Vinyasa)', 'mobility', 'min', 'mobility', 1180),
('acrobatic_gymnastics', 'Gym acrobatique', 'skill', 'min', 'skill', 1200),
('aerobic_gymnastics', 'Gym aerobic', 'cardio', 'min', 'skill', 1201),
('adventure_racing', 'Raid aventure', 'outdoor', 'km', 'mixed', 1202),
('arnis_eskrima', 'Arnis / Eskrima', 'combat', 'min', 'combat', 1203),
('arm_wrestling', 'Bras de fer sportif', 'force', 'min', 'strength', 1204),
('artistic_cycling', 'Cyclisme artistique', 'skill', 'min', 'cycling', 1205),
('australian_rules_football', 'Football australien', 'team', 'min', 'team', 1206),
('bandy', 'Bandy', 'team', 'min', 'team', 1207),
('beach_handball', 'Beach handball', 'team', 'min', 'team', 1208),
('beach_soccer', 'Beach soccer', 'team', 'min', 'football', 1209),
('beach_tennis', 'Beach tennis', 'cardio', 'min', 'racket', 1210),
('billiards_pool', 'Billard pool', 'skill', 'min', 'precision', 1211),
('blind_football', 'Cecifoot', 'team', 'min', 'football', 1212),
('bocce', 'Bocce', 'skill', 'min', 'precision', 1213),
('boccia', 'Boccia', 'skill', 'min', 'precision', 1214),
('bodyboarding', 'Bodyboard', 'outdoor', 'min', 'water', 1215),
('breakdance', 'Breaking', 'skill', 'min', 'skill', 1216),
('camogie', 'Camogie', 'team', 'min', 'team', 1217),
('canoe_polo', 'Canoe polo', 'team', 'min', 'water', 1218),
('cheerleading', 'Cheerleading', 'skill', 'min', 'skill', 1219),
('croquet', 'Croquet', 'skill', 'min', 'precision', 1220),
('cycle_ball', 'Cycle-ball', 'team', 'min', 'cycling', 1221),
('cycle_polo', 'Cycle polo', 'team', 'min', 'cycling', 1222),
('cyclocross', 'Cyclo-cross', 'outdoor', 'km', 'cycling', 1223),
('disc_golf', 'Disc golf', 'skill', 'min', 'precision', 1224),
('dodgeball', 'Dodgeball', 'team', 'min', 'team', 1225),
('dressage', 'Dressage', 'skill', 'min', 'skill', 1226),
('eventing', 'Concours complet', 'skill', 'min', 'skill', 1227),
('fell_running', 'Course en montagne', 'outdoor', 'km', 'trail', 1228),
('finswimming', 'Nage avec palmes', 'endurance', 'm', 'swimming', 1229),
('freestyle_wrestling', 'Lutte libre', 'combat', 'min', 'combat', 1230),
('futnet', 'Futnet', 'team', 'min', 'team', 1231),
('gaelic_football', 'Football gaelique', 'team', 'min', 'team', 1232),
('goalball', 'Goalball', 'team', 'min', 'team', 1233),
('grappling', 'Grappling', 'combat', 'min', 'combat', 1234),
('greco_roman_wrestling', 'Lutte greco-romaine', 'combat', 'min', 'combat', 1235),
('grip_sport', 'Grip sport', 'force', 'min', 'strength', 1236),
('hapkido', 'Hapkido', 'combat', 'min', 'combat', 1237),
('highland_games', 'Highland games', 'force', 'min', 'strength', 1238),
('horse_racing', 'Course hippique', 'skill', 'min', 'skill', 1239),
('hurling', 'Hurling', 'team', 'min', 'team', 1240),
('ice_climbing', 'Cascade de glace', 'skill', 'min', 'climbing', 1241),
('inline_speed_skating', 'Roller vitesse', 'endurance', 'km', 'glide', 1242),
('kabaddi', 'Kabaddi', 'team', 'min', 'team', 1243),
('karting', 'Karting', 'skill', 'min', 'skill', 1244),
('kho_kho', 'Kho kho', 'team', 'min', 'team', 1245),
('motocross', 'Motocross', 'outdoor', 'min', 'skill', 1246),
('outrigger_canoe', 'Pirogue vaa', 'outdoor', 'km', 'water', 1247),
('para_cycling', 'Para cyclisme', 'endurance', 'km', 'cycling', 1248),
('para_powerlifting', 'Para powerlifting', 'force', 'kg', 'strength', 1249),
('petanque', 'Petanque', 'skill', 'min', 'precision', 1250),
('platform_tennis', 'Platform tennis', 'cardio', 'min', 'racket', 1251),
('polo', 'Polo', 'team', 'min', 'team', 1252),
('race_walking', 'Marche athletique', 'endurance', 'km', 'running', 1253),
('racketlon', 'Racketlon', 'cardio', 'min', 'racket', 1254),
('racquetball', 'Racquetball', 'cardio', 'min', 'racket', 1255),
('rafting', 'Rafting', 'outdoor', 'km', 'water', 1256),
('real_tennis', 'Jeu de paume', 'skill', 'min', 'racket', 1257),
('ringette', 'Ringette', 'team', 'min', 'team', 1258),
('rogaining', 'Rogaining', 'outdoor', 'km', 'hiking', 1259),
('sambo', 'Sambo', 'combat', 'min', 'combat', 1260),
('sepak_takraw', 'Sepak takraw', 'team', 'min', 'team', 1261),
('show_jumping', 'Saut d obstacles', 'skill', 'min', 'skill', 1262),
('sitting_volleyball', 'Volley assis', 'team', 'min', 'team', 1263),
('skimboarding', 'Skimboard', 'outdoor', 'min', 'water', 1264),
('ski_orienteering', 'Orientation a ski', 'outdoor', 'km', 'glide', 1265),
('snooker', 'Snooker', 'skill', 'min', 'precision', 1266),
('speed_skiing', 'Kilometre lance', 'outdoor', 'min', 'glide', 1267),
('sumo', 'Sumo', 'combat', 'min', 'combat', 1268),
('surfski', 'Surfski', 'outdoor', 'km', 'water', 1269),
('tchoukball', 'Tchoukball', 'team', 'min', 'team', 1270),
('telemark_skiing', 'Ski telemark', 'outdoor', 'km', 'glide', 1271),
('tug_of_war', 'Tir a la corde', 'force', 'min', 'strength', 1272),
('underwater_hockey', 'Hockey subaquatique', 'team', 'min', 'water', 1273),
('underwater_rugby', 'Rugby subaquatique', 'team', 'min', 'water', 1274),
('water_skiing', 'Ski nautique', 'outdoor', 'min', 'water', 1275),
('wheelchair_rugby', 'Rugby fauteuil', 'team', 'min', 'team', 1276),
('wheelchair_tennis', 'Tennis fauteuil', 'cardio', 'min', 'racket', 1277),
('wushu', 'Wushu', 'combat', 'min', 'combat', 1278)
on conflict (id) do nothing;
